'use client';
import React, { useEffect, useMemo, useState } from 'react';
import { LuArrowLeft, LuEye, LuEyeOff, LuPencil, LuPlus } from 'react-icons/lu';
import TabToggle from '@/app/ui/primitives/TabToggle/TabToggle';
import LabelDropdown from '@/app/ui/inputs/Dropdown/LabelDropdown';
import { Primary } from '@/app/ui/primitives/Buttons';
import CircleIconButton from '@/app/features/appointments/pages/AppointmentWorkspace/components/CircleIconButton';
import { useAppointmentWorkspaceStore } from '@/app/stores/appointmentWorkspaceStore';
import { useTaskStore } from '@/app/stores/taskStore';
import { useLoadTeam, useTeamForPrimaryOrg } from '@/app/hooks/useTeam';
import TaskFormFields from '@/app/features/tasks/components/TaskFormFields';
import { useTaskForm } from '@/app/hooks/useTaskForm';
import { getPreferredTimeZone } from '@/app/lib/timezone';
import {
  changeTaskStatus,
  loadTasksForPrimaryOrg,
  updateTask,
} from '@/app/features/tasks/services/taskService';
import type { Task, TaskStatus } from '@/app/features/tasks/types/task';
import type {
  EmployeeTaskCategory,
  ScheduleTask,
  ScheduleTaskStatus,
} from '@/app/features/appointments/types/workspace';
import {
  getTaskCategoryLabel,
  isSeriesTask,
  offsetToReminderValue,
  recurrenceToRepeatValue,
  TASK_REMINDER_OPTIONS,
  TASK_REPEAT_OPTIONS,
  type RecurrenceScope,
} from '@/app/features/tasks/constants/taskTaxonomy';
import RecurrenceScopeModal from '@/app/features/tasks/components/RecurrenceScopeModal';
import { formatStampDate } from '@/app/lib/appointmentWorkspace';

type TasksPanelProps = {
  appointmentId: string;
  /** The appointment's companion id — required to create parent (companion) tasks. */
  companionId?: string;
  /** Real parent/co-parent assignees for the appointment's companion. */
  parentOptions?: AssigneeOption[];
};

type TaskTab = 'EMPLOYEE' | 'PARENT';

const TABS = [
  { key: 'EMPLOYEE', label: 'Employee task' },
  { key: 'PARENT', label: 'Parent task' },
];

const STATUS_CLASSES: Record<ScheduleTaskStatus, string> = {
  COMPLETED: 'border-pill-success-border bg-pill-success-bg text-pill-success-text',
  UPCOMING: 'border-pill-info-border bg-pill-info-bg text-pill-info-text',
  CANCELLED: 'border-pill-warning-border bg-pill-warning-bg text-pill-warning-text',
  PENDING: 'border-pill-neutral-border bg-pill-neutral-bg text-pill-neutral-text',
};

const STATUS_OPTIONS: { label: string; value: ScheduleTaskStatus }[] = [
  { label: 'Upcoming', value: 'UPCOMING' },
  { label: 'Completed', value: 'COMPLETED' },
  { label: 'Cancelled', value: 'CANCELLED' },
  { label: 'Pending', value: 'PENDING' },
];

type AssigneeOption = { label: string; value: string };

// Include COMPLETED tasks: the backend list excludes them by default, which would
// drop completed rows from the panel and the Schedule timeline after a refresh.
const WORKSPACE_TASK_LOAD = { force: true, silent: true, filters: { includeCompleted: true } };

const taskStatusToScheduleStatus = (status: Task['status']): ScheduleTaskStatus => {
  if (status === 'COMPLETED') return 'COMPLETED';
  if (status === 'CANCELLED') return 'CANCELLED';
  if (status === 'IN_PROGRESS') return 'UPCOMING';
  return 'PENDING';
};

/** Map the workspace schedule status back to the backend Task status enum. */
const scheduleStatusToTaskStatus = (status: ScheduleTaskStatus): TaskStatus => {
  if (status === 'COMPLETED') return 'COMPLETED';
  if (status === 'CANCELLED') return 'CANCELLED';
  if (status === 'UPCOMING') return 'IN_PROGRESS';
  return 'PENDING';
};

/** "h:mm AM/PM" from a task's dueAt for the row's "Due:" line. */
const dueTimeLabel = (dueAt?: Date | string): string | undefined => {
  if (!dueAt) return undefined;
  const date = new Date(dueAt);
  if (Number.isNaN(date.getTime())) return undefined;
  return date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
};

const scheduleTaskFromTask = (task: Task): ScheduleTask => ({
  id: task._id,
  category: getTaskCategoryLabel(task.category) as EmployeeTaskCategory,
  // Title shows the task name; instructions render as the grey subtext line — same
  // mapping the Schedule timeline uses, so both surfaces render the row identically.
  description: task.name || task.description || 'Task',
  subtext: task.name ? task.description : undefined,
  assignedToId: task.assignedTo,
  status: taskStatusToScheduleStatus(task.status),
  time: dueTimeLabel(task.dueAt),
  startDate: task.dueAt ? new Date(task.dueAt).toISOString().slice(0, 10) : undefined,
  autoGenerated: task.source !== 'CUSTOM',
  sourceRefId: task.templateId || task.libraryTaskId,
});

const StatusPill = ({ status }: { status: ScheduleTaskStatus }) => (
  <span
    className={`inline-flex rounded-2xl border px-3 py-1 text-caption-1 ${STATUS_CLASSES[status]}`}
  >
    {STATUS_OPTIONS.find((o) => o.value === status)?.label ?? status}
  </span>
);

/** One "Task details" row inside the expandable breakdown. */
const DetailRow = ({ label, value }: { label: string; value: string }) => (
  <div className="flex items-start justify-between gap-4 border-b border-card-border py-2 last:border-0">
    <span className="text-caption-1 text-text-secondary">{label}</span>
    <span className="text-right text-body-4 text-text-primary">{value || '—'}</span>
  </div>
);

/** Read-only "Task details" breakdown shown when a row's view toggle is on. */
const TaskDetails = ({ detail, assignedByName }: { detail: Task; assignedByName?: string }) => {
  const reminderOffset = detail.reminder?.enabled ? detail.reminder.offsetMinutes : undefined;
  const reminderLabel =
    TASK_REMINDER_OPTIONS.find((o) => o.value === offsetToReminderValue(reminderOffset))?.label ??
    'No reminder';
  const repeatLabel =
    TASK_REPEAT_OPTIONS.find((o) => o.value === recurrenceToRepeatValue(detail.recurrence))
      ?.label ?? 'Does not repeat';
  const duration = [
    detail.dueAt ? formatStampDate(new Date(detail.dueAt).toISOString().slice(0, 10)) : undefined,
    detail.recurrence?.endDate
      ? formatStampDate(new Date(detail.recurrence.endDate).toISOString().slice(0, 10))
      : undefined,
  ]
    .filter(Boolean)
    .join(' - ');

  return (
    <div className="mt-2 rounded-2xl border border-card-border p-3">
      <p className="mb-1 text-caption-2 text-text-secondary">Task details</p>
      <DetailRow label="Category" value={getTaskCategoryLabel(detail.category)} />
      <DetailRow label="Repeat" value={repeatLabel} />
      <DetailRow label="Reminder" value={reminderLabel} />
      {duration && <DetailRow label="Duration" value={duration} />}
      {detail.description && <DetailRow label="Instructions" value={detail.description} />}
      {assignedByName && <DetailRow label="Assigned by" value={assignedByName} />}
    </div>
  );
};

const TaskRow = ({
  task,
  detail,
  assignedByName,
  assigneeOptions,
  onAssign,
  onStatus,
  onEdit,
  expanded,
  onToggleView,
  actionsDisabled = false,
  disabledReason,
}: {
  task: ScheduleTask;
  detail?: Task;
  assignedByName?: string;
  assigneeOptions: { label: string; value: string }[];
  onAssign: (option: { label: string; value: string }) => void;
  onStatus: (status: ScheduleTaskStatus) => void;
  onEdit: () => void;
  expanded: boolean;
  onToggleView: () => void;
  actionsDisabled?: boolean;
  disabledReason?: string;
}) => (
  <li className="flex flex-col gap-2 border-b border-card-border py-3 last:border-0">
    <div className="flex items-start justify-between gap-3">
      <div className="flex flex-col gap-1 leading-[130%]">
        <span className="text-body-4 text-text-primary">{task.description}</span>
        <span className="text-[12px] font-medium text-pill-success-text">
          {task.time ? `Due: ${task.time}` : ''}
          {task.startDate ? ` ${formatStampDate(task.startDate)}` : ''}
        </span>
      </div>
      <div className="flex items-center gap-2">
        {actionsDisabled ? (
          <StatusPill status={task.status} />
        ) : (
          <button
            type="button"
            aria-label={`Change status for ${task.description}`}
            onClick={() => {
              const order: ScheduleTaskStatus[] = ['UPCOMING', 'COMPLETED', 'CANCELLED', 'PENDING'];
              const next = order[(order.indexOf(task.status) + 1) % order.length];
              onStatus(next);
            }}
          >
            <StatusPill status={task.status} />
          </button>
        )}
      </div>
    </div>
    <div className="flex items-center justify-between gap-3">
      <div className="w-44">
        {actionsDisabled ? (
          <p className="rounded-2xl border border-card-border px-3 py-2 text-body-4 text-text-secondary">
            {task.assignedToName ?? task.assignedToId ?? 'Unassigned'}
          </p>
        ) : (
          <LabelDropdown
            placeholder="Assigned to"
            options={assigneeOptions}
            defaultOption={task.assignedToId ?? task.assignedToName}
            searchable={false}
            onSelect={(option) => onAssign({ label: option.label, value: option.value })}
          />
        )}
      </div>
      <div className="flex items-center gap-2">
        {/* View/hide toggle: expands the read-only Task details breakdown. */}
        <CircleIconButton
          icon={
            expanded ? (
              <LuEyeOff size={16} aria-hidden="true" />
            ) : (
              <LuEye size={16} aria-hidden="true" />
            )
          }
          label={expanded ? `Hide details for ${task.description}` : `View ${task.description}`}
          variant="dark"
          onClick={onToggleView}
        />
        <CircleIconButton
          icon={<LuPencil size={16} aria-hidden="true" />}
          label={`Edit ${task.description}`}
          onClick={onEdit}
          disabled={actionsDisabled}
        />
      </div>
    </div>
    {expanded && detail && <TaskDetails detail={detail} assignedByName={assignedByName} />}
    {actionsDisabled && disabledReason && (
      <p className="text-[12px] text-text-secondary">{disabledReason}</p>
    )}
  </li>
);

/**
 * Add/edit task form for the Quick Actions panel — the SAME shared TaskFormFields
 * + useTaskForm used by the main /tasks module, scoped to this appointment and the
 * active audience (Employee/Parent). Editing an existing task seeds the form.
 */
const PanelTaskForm = ({
  appointmentId,
  companionId,
  isParent,
  assignees,
  editingTask,
  onBack,
  onSaved,
}: {
  appointmentId: string;
  companionId?: string;
  isParent: boolean;
  assignees: AssigneeOption[];
  editingTask: Task | null;
  onBack: () => void;
  onSaved: () => void;
}) => {
  const audience = isParent ? 'PARENT_TASK' : 'EMPLOYEE_TASK';
  const {
    formData,
    setFormData,
    due,
    setDue,
    dueTimeValue,
    setDueTimeValue,
    formDataErrors,
    error,
    isLoading,
    templateOptions,
    selectTemplate,
    handleCreate,
  } = useTaskForm({
    isCompanionTask: isParent,
    initialTask: editingTask
      ? { ...editingTask, companionId: editingTask.companionId ?? companionId }
      : {
          appointmentId,
          audience,
          source: 'CUSTOM',
          dueAt: new Date(),
          // Parent (companion) tasks require the appointment's companion id.
          ...(isParent && companionId ? { companionId } : {}),
        },
    onSuccess: onSaved,
  });

  // New tasks go through handleCreate (validates + persists + resets). Editing an
  // existing task PATCHes it directly, preserving the appointment + audience.
  const [editError, setEditError] = useState<string | null>(null);
  const [scopeModalOpen, setScopeModalOpen] = useState(false);
  const [scopeBusy, setScopeBusy] = useState(false);

  const saveEdit = async (scope?: RecurrenceScope) => {
    setEditError(null);
    try {
      await updateTask({ ...formData, _id: editingTask!._id, appointmentId, audience }, scope);
      onSaved();
    } catch (err) {
      console.error('Failed to update task:', err);
      setEditError('Unable to update task. Please try again.');
    }
  };

  const persistScopedTask = async () => {
    if (!editingTask?._id) {
      await handleCreate();
      return;
    }
    // A task in a recurring series asks which occurrences the edit applies to.
    if (isSeriesTask(editingTask.recurrence)) {
      setScopeModalOpen(true);
      return;
    }
    await saveEdit();
  };

  const handleScopeConfirm = async (scope: RecurrenceScope) => {
    setScopeBusy(true);
    try {
      await saveEdit(scope);
      setScopeModalOpen(false);
    } finally {
      setScopeBusy(false);
    }
  };

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center gap-2">
        <CircleIconButton
          icon={<LuArrowLeft size={16} aria-hidden="true" />}
          label="Back to tasks"
          onClick={onBack}
        />
        <h3 className="text-body-2 font-bold text-text-primary">
          {editingTask ? 'Edit task' : 'New task'}
        </h3>
      </div>
      <TaskFormFields
        formData={formData}
        setFormData={setFormData}
        formDataErrors={formDataErrors}
        templateOptions={templateOptions}
        due={due}
        setDue={setDue}
        dueTimeValue={dueTimeValue}
        setDueTimeValue={setDueTimeValue}
        onSelectTemplate={selectTemplate}
        hideTemplatePicker={Boolean(editingTask)}
        showAssigneeSelect
        assigneeOptions={assignees}
        onAssigneeSelect={(option) => setFormData({ ...formData, assignedTo: option.value })}
      />
      {(error || editError) && <p className="text-caption-1 text-red-600">{error || editError}</p>}
      <div className="flex items-center gap-3">
        <Primary
          text={isLoading ? 'Saving…' : 'Save task'}
          onClick={() => void persistScopedTask()}
          isDisabled={isLoading}
        />
      </div>
      {scopeModalOpen && (
        <RecurrenceScopeModal
          showModal={scopeModalOpen}
          setShowModal={setScopeModalOpen}
          action="edit"
          taskName={editingTask?.name}
          busy={scopeBusy}
          onConfirm={handleScopeConfirm}
        />
      )}
    </div>
  );
};

/** Tasks panel: Employee (workspace schedule) + Parent task sub-tabs with a New/Edit form. */
const TasksPanel = ({ appointmentId, companionId, parentOptions = [] }: TasksPanelProps) => {
  const [tab, setTab] = useState<TaskTab>('EMPLOYEE');
  const [editingTask, setEditingTask] = useState<Task | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  // Row whose read-only "Task details" breakdown is expanded (view toggle).
  const [expandedRowId, setExpandedRowId] = useState<string | null>(null);

  useLoadTeam();
  const team = useTeamForPrimaryOrg();
  const employeeOptions = useMemo<AssigneeOption[]>(
    () =>
      team
        .map((member) => ({
          label: member.name?.trim() || member.practionerId,
          value: member.practionerId,
        }))
        .filter((option) => option.value),
    [team]
  );

  const encounter = useAppointmentWorkspaceStore((s) => s.encountersById[appointmentId]);
  const focusTaskId = useAppointmentWorkspaceStore((s) => s.focusTaskId);
  const setFocusTaskId = useAppointmentWorkspaceStore((s) => s.setFocusTaskId);
  const tasksById = useTaskStore((s) => s.tasksById);
  const [saveError, setSaveError] = useState<string | null>(null);
  const allTasks = useMemo(() => Object.values(tasksById), [tasksById]);

  useEffect(() => {
    // Force a fresh pull when the panel opens so newly-created/updated tasks for
    // this appointment always show.
    loadTasksForPrimaryOrg(WORKSPACE_TASK_LOAD).catch((error) => {
      console.error('Failed to load workspace tasks:', error);
    });
  }, []);

  // Opened from a schedule row's "View": auto-open that task's edit form, then
  // clear the focus flag so it doesn't re-trigger.
  useEffect(() => {
    if (!focusTaskId) return;
    const task = tasksById[focusTaskId];
    if (task) {
      setEditingTask(task);
      setFormOpen(true);
    }
    setFocusTaskId(null);
  }, [focusTaskId, tasksById, setFocusTaskId]);

  const isParent = tab === 'PARENT';
  const appointmentTasks = useMemo(
    () => allTasks.filter((task) => task.appointmentId === appointmentId),
    [allTasks, appointmentId]
  );
  const parentTasks = useMemo(
    () =>
      appointmentTasks.filter((task) => task.audience === 'PARENT_TASK').map(scheduleTaskFromTask),
    [appointmentTasks]
  );
  // Employee schedule tasks come solely from the task store (the single source of
  // truth shared with the Schedule timeline) so both surfaces render the same rows
  // and stay in sync — no local-only duplicates.
  const employeeTasks = useMemo(
    () =>
      appointmentTasks
        .filter((task) => task.audience === 'EMPLOYEE_TASK')
        .map(scheduleTaskFromTask),
    [appointmentTasks]
  );

  if (!encounter) return null;

  const openNew = () => {
    setEditingTask(null);
    setFormOpen(true);
  };

  const openEdit = (scheduleTask: ScheduleTask) => {
    const backing = tasksById[scheduleTask.id];
    if (backing) {
      setEditingTask(backing);
    } else {
      // Locally-generated schedule row not yet persisted — seed a draft Task.
      setEditingTask({
        _id: '',
        appointmentId,
        assignedTo: scheduleTask.assignedToId ?? '',
        audience: isParent ? 'PARENT_TASK' : 'EMPLOYEE_TASK',
        source: 'CUSTOM',
        category: scheduleTask.category,
        name: scheduleTask.description,
        description: scheduleTask.subtext ?? scheduleTask.description,
        dueAt: scheduleTask.startDate ? new Date(scheduleTask.startDate) : new Date(),
        timezone: getPreferredTimeZone(),
        status: 'PENDING',
      });
    }
    setFormOpen(true);
  };

  const closeForm = () => {
    setFormOpen(false);
    setEditingTask(null);
  };

  const assigneeOptions = isParent ? parentOptions : employeeOptions;

  // Persist an employee task change to the backend when the row is a real,
  // backend-issued task. Locally-generated schedule rows only update the
  // optimistic store. Backend failures roll the optimistic update back.
  const syncTaskToBackend = async (
    taskId: string,
    apply: (task: Task) => Task,
    runApi: (task: Task) => Promise<void>
  ) => {
    const existing = tasksById[taskId];
    if (!existing) return;
    setSaveError(null);
    try {
      await runApi(apply(existing));
    } catch (error) {
      console.error('Failed to sync task change:', error);
      setSaveError('Unable to update task. Please try again.');
      loadTasksForPrimaryOrg(WORKSPACE_TASK_LOAD).catch(() => undefined);
    }
  };

  // changeTaskStatus / updateTask optimistically upsert the task store (the source
  // both surfaces render from) and this handler rolls back via a refetch on failure,
  // so the Schedule timeline and this panel move together with no local duplicate.
  const handleEmployeeStatus = (taskId: string, status: ScheduleTaskStatus) => {
    void syncTaskToBackend(
      taskId,
      (task) => ({ ...task, status: scheduleStatusToTaskStatus(status) }),
      changeTaskStatus
    );
  };

  const handleEmployeeAssign = (taskId: string, option: AssigneeOption) => {
    void syncTaskToBackend(taskId, (task) => ({ ...task, assignedTo: option.value }), updateTask);
  };

  if (formOpen) {
    return (
      <PanelTaskForm
        appointmentId={appointmentId}
        companionId={companionId}
        isParent={isParent}
        assignees={assigneeOptions}
        editingTask={editingTask}
        onBack={closeForm}
        onSaved={() => {
          closeForm();
          loadTasksForPrimaryOrg(WORKSPACE_TASK_LOAD).catch(() => undefined);
        }}
      />
    );
  }

  const tasks = isParent ? parentTasks : employeeTasks;

  return (
    <div className="flex flex-col gap-4">
      <TabToggle
        tabs={TABS}
        activeKey={tab}
        onChange={(key) => setTab(key as TaskTab)}
        panelId={(key) => `tasks-panel-${key}`}
      />
      {tasks.length === 0 ? (
        <p className="py-6 text-center text-body-4 text-text-secondary">No tasks yet.</p>
      ) : (
        <ul className="rounded-2xl border border-card-border px-4">
          {tasks.map((task) => (
            <TaskRow
              key={task.id}
              task={task}
              detail={tasksById[task.id]}
              assigneeOptions={assigneeOptions}
              // Parent tasks are owned by the mobile parent app — assign/status are
              // disabled here (with a reason) until that contract is wired, rather
              // than silently doing nothing. Viewing details stays available.
              actionsDisabled={isParent}
              disabledReason={
                isParent ? 'Parent tasks are managed from the pet parent app.' : undefined
              }
              onAssign={(option) => handleEmployeeAssign(task.id, option)}
              onStatus={(status) => handleEmployeeStatus(task.id, status)}
              onEdit={() => openEdit(task)}
              expanded={expandedRowId === task.id}
              onToggleView={() =>
                setExpandedRowId((current) => (current === task.id ? null : task.id))
              }
            />
          ))}
        </ul>
      )}
      <div className="flex justify-center">
        {saveError && <p className="text-caption-1 text-red-600">{saveError}</p>}
        <Primary text="New Task" icon={<LuPlus aria-hidden="true" />} onClick={openNew} />
      </div>
    </div>
  );
};

export default TasksPanel;
