'use client';
import React, { useEffect, useMemo, useState } from 'react';
import { LuArrowLeft, LuCalendarClock, LuPencil, LuPlus } from 'react-icons/lu';
import TabToggle from '@/app/ui/primitives/TabToggle/TabToggle';
import LabelDropdown from '@/app/ui/inputs/Dropdown/LabelDropdown';
import Datepicker from '@/app/ui/inputs/Datepicker';
import Timepicker from '@/app/ui/inputs/Timepicker';
import { Primary, Secondary } from '@/app/ui/primitives/Buttons';
import CircleIconButton from '@/app/features/appointments/pages/AppointmentWorkspace/components/CircleIconButton';
import { useAppointmentWorkspaceStore } from '@/app/stores/appointmentWorkspaceStore';
import { useTaskStore } from '@/app/stores/taskStore';
import { useLoadTeam, useTeamForPrimaryOrg } from '@/app/hooks/useTeam';
import {
  changeTaskStatus,
  createTask,
  loadTasksForPrimaryOrg,
  updateTask,
} from '@/app/features/tasks/services/taskService';
import type { RecurrenceType, Task, TaskStatus } from '@/app/features/tasks/types/task';
import type {
  EmployeeTaskCategory,
  ScheduleTask,
  ScheduleTaskStatus,
} from '@/app/features/appointments/types/workspace';
import { formatStampDate } from '@/app/lib/appointmentWorkspace';

type TasksPanelProps = {
  appointmentId: string;
  /** Real parent/co-parent assignees for the appointment's companion. */
  parentOptions?: AssigneeOption[];
};

type TaskTab = 'EMPLOYEE' | 'PARENT';

const TABS = [
  { key: 'EMPLOYEE', label: 'Employee task' },
  { key: 'PARENT', label: 'Parent task' },
];

const STATUS_CLASSES: Record<ScheduleTaskStatus, string> = {
  COMPLETED: 'border-pill-success-border bg-pill-success-bg text-pill-success-text',
  UPCOMING: 'border-pill-info-border bg-pill-info-bg text-pill-info-text',
  CANCELLED: 'border-pill-warning-border bg-pill-warning-bg text-pill-warning-text',
  PENDING: 'border-pill-neutral-border bg-pill-neutral-bg text-pill-neutral-text',
};

const STATUS_OPTIONS: { label: string; value: ScheduleTaskStatus }[] = [
  { label: 'Upcoming', value: 'UPCOMING' },
  { label: 'Completed', value: 'COMPLETED' },
  { label: 'Cancelled', value: 'CANCELLED' },
  { label: 'Pending', value: 'PENDING' },
];

const EMPLOYEE_CATEGORIES: { label: string; value: EmployeeTaskCategory }[] = [
  'Consultation (billable)',
  'Medication',
  'Care',
  'Treatment',
  'Diagnostic',
  'Communication',
  'Billing',
  'Record',
  'SOAP',
  'Admin',
  'Custom',
].map((c) => ({ label: c, value: c as EmployeeTaskCategory }));

const PARENT_CATEGORIES: { label: string; value: EmployeeTaskCategory }[] = [
  'Medication',
  'Care',
  'Diet',
  'Communication',
  'Billing',
  'Record',
  'Custom reminders',
].map((c) => ({ label: c, value: c as EmployeeTaskCategory }));

type AssigneeOption = { label: string; value: string };

const REPEAT_OPTIONS = ['None', 'Daily', 'Weekly', 'Monthly'].map((r) => ({ label: r, value: r }));

const taskStatusToScheduleStatus = (status: Task['status']): ScheduleTaskStatus => {
  if (status === 'COMPLETED') return 'COMPLETED';
  if (status === 'CANCELLED') return 'CANCELLED';
  if (status === 'IN_PROGRESS') return 'UPCOMING';
  return 'PENDING';
};

/** Map the workspace schedule status back to the backend Task status enum. */
const scheduleStatusToTaskStatus = (status: ScheduleTaskStatus): TaskStatus => {
  if (status === 'COMPLETED') return 'COMPLETED';
  if (status === 'CANCELLED') return 'CANCELLED';
  if (status === 'UPCOMING') return 'IN_PROGRESS';
  return 'PENDING';
};

const repeatToRecurrenceType = (repeat: string): RecurrenceType => {
  if (repeat === 'Daily') return 'DAILY';
  if (repeat === 'Weekly') return 'WEEKLY';
  return 'ONCE';
};

/** "YYYY-MM-DD" (draft storage) ⇄ the Datepicker's `Date | null` value. */
const parseDraftDate = (value?: string): Date | null => {
  if (!value) return null;
  const date = new Date(`${value}T00:00:00`);
  return Number.isNaN(date.getTime()) ? null : date;
};
const formatDraftDate = (date: Date | null): string => {
  if (!date) return '';
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

const buildDueAt = (dateValue: string, timeValue: string) => {
  const date = dateValue || new Date().toISOString().slice(0, 10);
  const time = timeValue || '09:00';
  return new Date(`${date}T${time}:00`);
};

const scheduleTaskFromTask = (task: Task): ScheduleTask => ({
  id: task._id,
  category: task.category as EmployeeTaskCategory,
  description: task.description || task.name,
  assignedToId: task.assignedTo,
  status: taskStatusToScheduleStatus(task.status),
  startDate: task.dueAt ? new Date(task.dueAt).toISOString().slice(0, 10) : undefined,
  autoGenerated: task.source !== 'CUSTOM',
  sourceRefId: task.templateId || task.libraryTaskId,
});

const StatusPill = ({ status }: { status: ScheduleTaskStatus }) => (
  <span
    className={`inline-flex rounded-2xl border px-3 py-1 text-caption-1 ${STATUS_CLASSES[status]}`}
  >
    {STATUS_OPTIONS.find((o) => o.value === status)?.label ?? status}
  </span>
);

const TaskRow = ({
  task,
  assigneeOptions,
  onAssign,
  onStatus,
  onEdit,
  onReschedule,
  actionsDisabled = false,
  disabledReason,
}: {
  task: ScheduleTask;
  assigneeOptions: { label: string; value: string }[];
  onAssign: (option: { label: string; value: string }) => void;
  onStatus: (status: ScheduleTaskStatus) => void;
  onEdit: () => void;
  onReschedule: () => void;
  actionsDisabled?: boolean;
  disabledReason?: string;
}) => (
  <li className="flex flex-col gap-2 border-b border-card-border py-3 last:border-0">
    <div className="flex items-start justify-between gap-3">
      <div className="flex flex-col gap-1 leading-[130%]">
        <span className="text-[12px] font-medium text-pill-success-text">
          {task.startDate ? formatStampDate(task.startDate) : 'No date'}
        </span>
        <span className="text-[12px] text-text-secondary">{task.category}</span>
        <span className="text-body-4 text-text-primary">{task.description}</span>
      </div>
      <div className="flex items-center gap-2">
        <CircleIconButton
          icon={<LuPencil size={16} aria-hidden="true" />}
          label={`Edit ${task.description}`}
          variant="dark"
          onClick={onEdit}
        />
        <CircleIconButton
          icon={<LuCalendarClock size={16} aria-hidden="true" />}
          label={`Reschedule ${task.description}`}
          onClick={onReschedule}
          disabled={actionsDisabled}
        />
      </div>
    </div>
    <div className="flex items-center justify-between gap-3">
      <div className="w-44">
        {actionsDisabled ? (
          <p className="rounded-2xl border border-card-border px-3 py-2 text-body-4 text-text-secondary">
            {task.assignedToName ?? task.assignedToId ?? 'Unassigned'}
          </p>
        ) : (
          <LabelDropdown
            placeholder="Assigned to"
            options={assigneeOptions}
            defaultOption={task.assignedToId ?? task.assignedToName}
            searchable={false}
            onSelect={(option) => onAssign({ label: option.label, value: option.value })}
          />
        )}
      </div>
      {actionsDisabled ? (
        <StatusPill status={task.status} />
      ) : (
        <button
          type="button"
          aria-label={`Change status for ${task.description}`}
          onClick={() => {
            const order: ScheduleTaskStatus[] = ['UPCOMING', 'COMPLETED', 'CANCELLED', 'PENDING'];
            const next = order[(order.indexOf(task.status) + 1) % order.length];
            onStatus(next);
          }}
        >
          <StatusPill status={task.status} />
        </button>
      )}
    </div>
    {actionsDisabled && disabledReason && (
      <p className="text-[12px] text-text-secondary">{disabledReason}</p>
    )}
  </li>
);

type TaskDraft = {
  assignedTo: string;
  templateSource: string;
  category: EmployeeTaskCategory;
  description: string;
  setTime: string;
  reminder: string;
  repeat: string;
  starts: string;
  ends: string;
};

const EMPTY_DRAFT: TaskDraft = {
  assignedTo: '',
  templateSource: 'YC Library',
  category: 'Care',
  description: '',
  setTime: '',
  reminder: '',
  repeat: 'None',
  starts: '',
  ends: '',
};

const TaskForm = ({
  isParent,
  draft,
  onChange,
  onSave,
  onDiscard,
  editing,
  assignees,
}: {
  isParent: boolean;
  draft: TaskDraft;
  onChange: (patch: Partial<TaskDraft>) => void;
  onSave: () => void;
  onDiscard: () => void;
  editing: boolean;
  assignees: AssigneeOption[];
}) => {
  const categories = isParent ? PARENT_CATEGORIES : EMPLOYEE_CATEGORIES;
  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center gap-2">
        <CircleIconButton
          icon={<LuArrowLeft size={16} aria-hidden="true" />}
          label="Back to tasks"
          onClick={onDiscard}
        />
        <h3 className="text-body-2 font-bold text-text-primary">
          {editing ? 'Edit Task' : 'New Task'}
        </h3>
      </div>
      <LabelDropdown
        placeholder="Assigned to"
        options={assignees}
        defaultOption={draft.assignedTo}
        searchable={false}
        onSelect={(o) => onChange({ assignedTo: o.value })}
      />
      <div className="grid grid-cols-2 gap-3">
        <LabelDropdown
          placeholder="Template source"
          options={[
            { label: 'YC Library', value: 'YC Library' },
            { label: 'Custom', value: 'Custom' },
          ]}
          defaultOption={draft.templateSource}
          searchable={false}
          onSelect={(o) => onChange({ templateSource: o.value })}
        />
        <LabelDropdown
          placeholder="Category"
          options={categories}
          defaultOption={draft.category}
          searchable={false}
          onSelect={(o) => onChange({ category: o.value as EmployeeTaskCategory })}
        />
      </div>
      <textarea
        value={draft.description}
        onChange={(e) => onChange({ description: e.target.value })}
        aria-label="Task description"
        rows={3}
        placeholder="Describe the task"
        className="rounded-2xl border border-input-border-default px-4 py-2.5 text-body-4 text-text-primary outline-none focus:border-input-border-active"
      />
      <div className="grid grid-cols-2 gap-3">
        <Timepicker
          label="Set time"
          value={draft.setTime}
          onChange={(value) => onChange({ setTime: value })}
        />
        <input
          value={draft.reminder}
          onChange={(e) => onChange({ reminder: e.target.value })}
          aria-label="Reminder before"
          placeholder="Reminder before"
          className="rounded-2xl border border-input-border-default px-4 py-2.5 text-body-4 text-text-primary outline-none focus:border-input-border-active"
        />
      </div>
      <LabelDropdown
        placeholder="Repeat"
        options={REPEAT_OPTIONS}
        defaultOption={draft.repeat}
        searchable={false}
        onSelect={(o) => onChange({ repeat: o.value })}
      />
      <div className="grid grid-cols-2 gap-3">
        <Datepicker
          type="input"
          placeholder="Starts"
          currentDate={parseDraftDate(draft.starts)}
          setCurrentDate={
            ((next: Date | null) => onChange({ starts: formatDraftDate(next) })) as React.Dispatch<
              React.SetStateAction<Date | null>
            >
          }
        />
        <Datepicker
          type="input"
          placeholder="Ends"
          currentDate={parseDraftDate(draft.ends)}
          setCurrentDate={
            ((next: Date | null) => onChange({ ends: formatDraftDate(next) })) as React.Dispatch<
              React.SetStateAction<Date | null>
            >
          }
        />
      </div>
      <div className="flex items-center gap-3">
        <Primary text="Save task" onClick={onSave} />
        <Secondary text="Discard" onClick={onDiscard} />
      </div>
    </div>
  );
};

/** Tasks panel: Employee (workspace schedule) + Parent task sub-tabs with a New/Edit form. */
const TasksPanel = ({ appointmentId, parentOptions = [] }: TasksPanelProps) => {
  const [tab, setTab] = useState<TaskTab>('EMPLOYEE');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [draft, setDraft] = useState<TaskDraft>(EMPTY_DRAFT);

  useLoadTeam();
  const team = useTeamForPrimaryOrg();
  const employeeOptions = useMemo<AssigneeOption[]>(
    () =>
      team
        .map((member) => ({
          label: member.name?.trim() || member.practionerId,
          value: member.practionerId,
        }))
        .filter((option) => option.value),
    [team]
  );

  const encounter = useAppointmentWorkspaceStore((s) => s.encountersById[appointmentId]);
  const addScheduleTask = useAppointmentWorkspaceStore((s) => s.addScheduleTask);
  const updateScheduleTask = useAppointmentWorkspaceStore((s) => s.updateScheduleTask);
  const setScheduleTaskStatus = useAppointmentWorkspaceStore((s) => s.setScheduleTaskStatus);
  const tasksById = useTaskStore((s) => s.tasksById);
  const [saveError, setSaveError] = useState<string | null>(null);
  const allTasks = useMemo(() => Object.values(tasksById), [tasksById]);

  useEffect(() => {
    loadTasksForPrimaryOrg({ silent: true }).catch((error) => {
      console.error('Failed to load workspace tasks:', error);
    });
  }, []);

  const isParent = tab === 'PARENT';
  const appointmentTasks = useMemo(
    () => allTasks.filter((task) => task.appointmentId === appointmentId),
    [allTasks, appointmentId]
  );
  const parentTasks = useMemo(
    () =>
      appointmentTasks.filter((task) => task.audience === 'PARENT_TASK').map(scheduleTaskFromTask),
    [appointmentTasks]
  );
  const employeeTasks = useMemo(
    () => [
      ...(encounter?.schedule ?? []),
      ...appointmentTasks
        .filter((task) => task.audience === 'EMPLOYEE_TASK')
        .map(scheduleTaskFromTask),
    ],
    [appointmentTasks, encounter?.schedule]
  );

  if (!encounter) return null;

  const openNew = () => {
    setDraft(EMPTY_DRAFT);
    setEditingId(null);
    setFormOpen(true);
  };

  const openEdit = (task: ScheduleTask) => {
    setDraft({
      assignedTo: task.assignedToId ?? '',
      templateSource: 'YC Library',
      category: task.category,
      description: task.description,
      setTime: '',
      reminder: '',
      repeat: 'None',
      starts: task.startDate ?? '',
      ends: task.endDate ?? '',
    });
    setEditingId(task.id);
    setFormOpen(true);
  };

  const closeForm = () => {
    setFormOpen(false);
    setEditingId(null);
  };

  const assigneeOptions = isParent ? parentOptions : employeeOptions;

  const handleSave = async () => {
    const assignee = assigneeOptions.find((a) => a.value === draft.assignedTo);
    const base: Omit<ScheduleTask, 'id'> = {
      description: draft.description,
      category: draft.category,
      assignedToId: draft.assignedTo || undefined,
      assignedToName: assignee?.label,
      status: 'UPCOMING',
      startDate: draft.starts || undefined,
      endDate: draft.ends || undefined,
      autoGenerated: false,
    };
    const taskPayload: Task = {
      _id: '',
      appointmentId,
      assignedTo: draft.assignedTo,
      audience: isParent ? 'PARENT_TASK' : 'EMPLOYEE_TASK',
      source: 'CUSTOM',
      category: draft.category,
      name: draft.description || draft.category,
      description: draft.description,
      dueAt: buildDueAt(draft.starts, draft.setTime),
      recurrence: {
        type: repeatToRecurrenceType(draft.repeat),
        isMaster: draft.repeat !== 'None',
        endDate: draft.ends ? new Date(`${draft.ends}T23:59:59`) : undefined,
      },
      reminder: draft.reminder
        ? { enabled: true, offsetMinutes: Number.parseInt(draft.reminder, 10) || 0 }
        : undefined,
      status: 'PENDING',
    };
    if (editingId) {
      if (!isParent) updateScheduleTask(appointmentId, editingId, base);
    } else {
      setSaveError(null);
      try {
        await createTask(taskPayload);
        if (!isParent) addScheduleTask(appointmentId, base);
      } catch (error) {
        console.error('Failed to create workspace task:', error);
        setSaveError('Unable to save task. Please try again.');
        return;
      }
    }
    closeForm();
  };

  // Persist an employee task change to the backend when the row is a real,
  // backend-issued task (its id is a key in tasksById). Locally-generated
  // schedule rows (e.g. inpatient template tasks not yet persisted) only update
  // the optimistic store. Backend failures roll the optimistic update back.
  const syncTaskToBackend = async (
    taskId: string,
    apply: (task: Task) => Task,
    runApi: (task: Task) => Promise<void>
  ) => {
    const existing = tasksById[taskId];
    if (!existing) return;
    setSaveError(null);
    try {
      await runApi(apply(existing));
    } catch (error) {
      console.error('Failed to sync task change:', error);
      setSaveError('Unable to update task. Please try again.');
      // Re-pull authoritative state so the optimistic row does not drift.
      loadTasksForPrimaryOrg({ force: true, silent: true }).catch(() => undefined);
    }
  };

  const handleEmployeeStatus = (taskId: string, status: ScheduleTaskStatus) => {
    setScheduleTaskStatus(appointmentId, taskId, status);
    void syncTaskToBackend(
      taskId,
      (task) => ({ ...task, status: scheduleStatusToTaskStatus(status) }),
      changeTaskStatus
    );
  };

  const handleEmployeeAssign = (taskId: string, option: AssigneeOption) => {
    updateScheduleTask(appointmentId, taskId, {
      assignedToId: option.value,
      assignedToName: option.label,
    });
    void syncTaskToBackend(taskId, (task) => ({ ...task, assignedTo: option.value }), updateTask);
  };

  if (formOpen) {
    return (
      <TaskForm
        isParent={isParent}
        draft={draft}
        editing={editingId != null}
        assignees={assigneeOptions}
        onChange={(patch) => setDraft((prev) => ({ ...prev, ...patch }))}
        onSave={handleSave}
        onDiscard={closeForm}
      />
    );
  }

  const tasks = isParent ? parentTasks : employeeTasks;

  return (
    <div className="flex flex-col gap-4">
      <TabToggle
        tabs={TABS}
        activeKey={tab}
        onChange={(key) => setTab(key as TaskTab)}
        panelId={(key) => `tasks-panel-${key}`}
      />
      {tasks.length === 0 ? (
        <p className="py-6 text-center text-body-4 text-text-secondary">No tasks yet.</p>
      ) : (
        <ul className="rounded-2xl border border-card-border px-4">
          {tasks.map((task) => (
            <TaskRow
              key={task.id}
              task={task}
              assigneeOptions={assigneeOptions}
              // Parent tasks are owned by the mobile parent app — assign/status/
              // reschedule are disabled here (with a reason) until that contract
              // is wired, rather than silently doing nothing.
              actionsDisabled={isParent}
              disabledReason={
                isParent ? 'Parent tasks are managed from the pet parent app.' : undefined
              }
              onAssign={(option) => handleEmployeeAssign(task.id, option)}
              onStatus={(status) => handleEmployeeStatus(task.id, status)}
              onEdit={() => openEdit(task)}
              // Reschedule opens the edit form (real date/time pickers); saving
              // persists via the task API — no more hardcoded placeholder date.
              onReschedule={() => openEdit(task)}
            />
          ))}
        </ul>
      )}
      <div className="flex justify-center">
        {saveError && <p className="text-caption-1 text-red-600">{saveError}</p>}
        <Primary text="New Task" icon={<LuPlus aria-hidden="true" />} onClick={openNew} />
      </div>
    </div>
  );
};

export default TasksPanel;
