import { AppointmentsProps } from "@/app/types/appointments";

export const demoAppointments: AppointmentsProps[] = [
  {
    name: "Bella",
    parentName: "Sarah Johnson",
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    reason: "Annual vaccination",
    emergency: false,
    breed: "Golden Retriever",
    species: "Dog",
    room: "Room 3A",
    time: "10:30 AM",
    date: "2025-11-06",
    lead: "Dr. Emily Carter",
    leadDepartment: "Veterinary Medicine",
    support: ["Nurse Rachel", "Assistant Tom"],
    status: "Requested",
    service: "General Consult",
  },
  {
    name: "Milo",
    parentName: "John Smith",
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    reason: "Limping after walk",
    emergency: true,
    breed: "Beagle",
    species: "Dog",
    room: "Emergency Bay 1",
    time: "9:15 AM",
    date: "2025-11-06",
    lead: "Dr. Mark Daniels",
    leadDepartment: "Orthopedics",
    support: ["Nurse Rachel", "Assistant Tom"],
    status: "Upcoming",
    service: "General Consult",
  },
  {
    name: "Luna",
    parentName: "Priya Mehta",
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    reason: "Dental cleaning",
    emergency: false,
    breed: "Persian",
    species: "Cat",
    room: "Room 2B",
    time: "1:00 PM",
    date: "2025-11-06",
    lead: "Dr. Rebecca Lin",
    leadDepartment: "Dentistry",
    status: "Checked-in",
    support: ["Nurse Rachel", "Assistant Tom"],
    service: "General Consult",
  },
  {
    name: "Rocky",
    parentName: "David Lee",
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    reason: "Regular checkup",
    emergency: false,
    breed: "Bulldog",
    species: "Dog",
    room: "Room 4C",
    time: "11:45 AM",
    date: "2025-11-06",
    lead: "Dr. Michael Brown",
    leadDepartment: "General Care",
    support: ["Nurse Rachel", "Assistant Tom"],
    status: "In-progress",
    service: "General Consult",
  },
  {
    name: "Coco",
    parentName: "Elena Garcia",
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    reason: "Skin rash and itching",
    emergency: false,
    breed: "Poodle",
    species: "Dog",
    room: "Room 1A",
    time: "3:30 PM",
    date: "2025-11-06",
    lead: "Dr. Jason Patel",
    leadDepartment: "Dermatology",
    status: "Completed",
    support: ["Nurse Rachel", "Assistant Tom"],
    service: "General Consult",
  },
];
