/** The five workspace steps, in order. */
export type WorkspaceStep = 'SOAP' | 'DIAGNOSTICS' | 'TREATMENT' | 'INVOICE' | 'SUMMARY';

export const WORKSPACE_STEPS: WorkspaceStep[] = [
  'SOAP',
  'DIAGNOSTICS',
  'TREATMENT',
  'INVOICE',
  'SUMMARY',
];

export const WORKSPACE_STEP_LABELS: Record<WorkspaceStep, string> = {
  SOAP: 'SOAP Notes',
  DIAGNOSTICS: 'Diagnostics',
  TREATMENT: 'Treatment',
  INVOICE: 'Invoice',
  SUMMARY: 'Summary',
};

export type StepStatus = 'EMPTY' | 'IN_PROGRESS' | 'COMPLETED' | 'LOCKED';

export type EncounterMode = 'OUTPATIENT' | 'INPATIENT';

export type AlertSeverity = 'CAUTION' | 'MEDICAL' | 'INFO' | 'ATTENTION' | 'ADMIN';

export type CompanionAlert = {
  id: string;
  label: string;
  severity: AlertSeverity;
};

/** A green "ready" stamp records who toggled it and when. */
export type ReadyState = {
  value: boolean;
  byUserId?: string;
  byName?: string;
  at?: string;
};

/** Rich-text content is stored as sanitized HTML for backend round-trips. */
export type RichTextValue = string;

export type SoapNoteEntry = {
  id: string;
  chiefComplaint: RichTextValue;
  subjective: RichTextValue;
  objective: RichTextValue;
  assessment: RichTextValue;
  plan: RichTextValue;
  templateId?: string;
  signedByName?: string;
  signedAt?: string;
  signedOffline?: boolean;
  status: StepStatus;
  createdAt: string;
};

export type SoapTemplate = {
  id: string;
  name: string;
  serviceId?: string;
  isDefault?: boolean;
};

export type Vitals = {
  id: string;
  code: string;
  weightLbs?: number;
  tempF?: number;
  heartRateBpm?: number;
  respRateBpm?: number;
  crtSec?: string;
  mucousMembrane?: string;
  painScore?: number;
  bcs?: number;
  notes?: string;
  recordedByName: string;
  recordedAt: string;
};

export type ObservationToolKey = 'FGS' | 'CSU_CAP';

export type ObservationToolDefinition = {
  key: ObservationToolKey;
  name: string;
  intro: string;
};

export type ObservationRecord = {
  id: string;
  code: string;
  toolKey: ObservationToolKey | string;
  toolName: string;
  scores: Record<string, number | string>;
  total?: number;
  recordedByName: string;
  recordedAt: string;
};

export type DiagnosticOrderStatus = 'CREATED' | 'SUBMITTED' | 'COMPLETED';

export type DiagnosticResultRow = {
  test: string;
  value: string;
  reference: string;
  meter: string;
};

export type DiagnosticOrder = {
  id: string;
  orderCode: string;
  createdAt: string;
  status: DiagnosticOrderStatus;
  results?: DiagnosticResultRow[];
};

export type DiagnosticTestCard = {
  id: string;
  name: string;
  priceCents: number;
  currency?: string;
  orderCode?: string;
  turnaround?: string;
  specimen?: string;
};

export type LineItemKind = 'SERVICE' | 'PACKAGE';

/** A component line shown when a package line item is expanded. */
export type LineItemBreakdown = {
  id: string;
  name: string;
  qty: number;
  instructions?: string;
  amountCents: number;
};

export type LineItem = {
  id: string;
  refId: string;
  kind: LineItemKind;
  name: string;
  qty: number;
  instructions?: string;
  unitPriceCents: number;
  amountCents: number;
  breakdown?: LineItemBreakdown[];
};

export type PrescriptionFulfillment = 'IN_HOUSE' | 'PRESCRIPTION_ONLY';

export type PrescriptionItem = {
  id: string;
  medicineName: string;
  dosage?: string;
  route?: string;
  frequency?: string;
  durationDays?: string;
  instructions?: string;
  fulfillment: PrescriptionFulfillment;
};

/** Full employee + schedule task category set. */
export type EmployeeTaskCategory =
  | 'Consultation (billable)'
  | 'Medication'
  | 'Care'
  | 'Treatment'
  | 'Diagnostic'
  | 'Communication'
  | 'Billing'
  | 'Record'
  | 'SOAP'
  | 'Admin'
  | 'Custom';

/** Restricted parent-task category set (Record => Observation Tool only). */
export type ParentTaskCategory =
  | 'Medication'
  | 'Care'
  | 'Diet'
  | 'Communication'
  | 'Billing'
  | 'Record'
  | 'Custom reminders';

export type ScheduleTaskCategory = EmployeeTaskCategory;

export type TaskRepeat = 'None' | 'Daily' | 'Weekly' | 'Monthly';

export type TaskAssigneeKind = 'EMPLOYEE' | 'PARENT' | 'CO_PARENT';

export type ScheduleTaskStatus = 'UPCOMING' | 'COMPLETED' | 'CANCELLED' | 'PENDING';

export type ScheduleTask = {
  id: string;
  time?: string;
  description: string;
  category: ScheduleTaskCategory;
  assignedToId?: string;
  assignedToName?: string;
  status: ScheduleTaskStatus;
  startDate?: string;
  endDate?: string;
  autoGenerated: boolean;
  sourceRefId?: string;
};

export type PaymentMethod = 'ONLINE' | 'CASH' | 'CARD' | 'DEPOSIT';

export type InvoiceStatus = 'PAID_FULL' | 'UNPAID' | 'PARTIAL';

export type InvoiceLineItem = {
  id: string;
  name: string;
  unitPriceCents: number;
  qty: number;
  grossCents: number;
  discountCents: number;
  amountCents: number;
};

export type PastInvoice = {
  id: string;
  createdAt: string;
  totalCents: number;
  outstandingCents: number;
  status: InvoiceStatus;
  byName?: string;
  items: InvoiceLineItem[];
};

export type WorkspaceDocumentCategory =
  | 'SOAP'
  | 'Diagnostics'
  | 'Treatment'
  | 'Invoice'
  | 'Discharge'
  | 'Consent';

export type WorkspaceDocument = {
  id: string;
  createdAt: string;
  category: WorkspaceDocumentCategory;
  description: string;
  signedByName?: string;
  lastModifiedAt: string;
  signatureRequired?: boolean;
};

export type RoomUnit = {
  id: string;
  name: string;
  occupied: boolean;
};

export type AppointmentEncounter = {
  appointmentId: string;
  mode: EncounterMode;
  consultationType: string;
  leadId?: string;
  leadName?: string;
  nurseId?: string;
  nurseName?: string;
  alerts: CompanionAlert[];
  soap: SoapNoteEntry[];
  soapTemplates: SoapTemplate[];
  vitals: Vitals[];
  observations: ObservationRecord[];
  diagnosticTests: DiagnosticTestCard[];
  diagnosticOrders: DiagnosticOrder[];
  services: LineItem[];
  prescription: PrescriptionItem[];
  schedule: ScheduleTask[];
  roomId?: string;
  unitId?: string;
  invoiceLineItems: InvoiceLineItem[];
  pastInvoices: PastInvoice[];
  depositCents: number;
  withdrawDeposit: boolean;
  taxPercent: number;
  overallDiscountPercent: number;
  dischargeSummary: RichTextValue;
  followUpAt?: string;
  documents: WorkspaceDocument[];
  readyForBilling: ReadyState;
  readyForDischarge: ReadyState;
  stepStatus: Record<WorkspaceStep, StepStatus>;
  lockedAt?: string;
  viewOnly: boolean;
};

export type SideAction = 'RECORD' | 'TASKS' | 'DOCUMENTS' | 'CHAT' | 'ACTIVITY' | 'MSD';
