import { TasksProps } from "@/app/types/tasks";

export const demoTasks: TasksProps[] = [
  {
    task: "Follow up with new client",
    description: "Send onboarding documents and schedule first meeting.",
    category: "Client Relations",
    from: "John Carter",
    to: "Evergreen Veterinary Clinic",
    toLabel: "Organisations",
    due: "2025-11-07",
    status: "Upcoming",
  },
  {
    task: "Update vaccination records",
    description: "Verify and upload updated vaccine certificates for pets.",
    category: "Records Management",
    from: "Emily Davis",
    to: "Sarah Wilson",
    toLabel: "Companions",
    due: "2025-11-08",
    status: "In-progress",
  },
  {
    task: "Prepare monthly billing report",
    description: "Generate and review invoices for October.",
    category: "Finance",
    from: "Michael Brown",
    to: "Happy Tails Clinic",
    toLabel: "Organisations",
    due: "2025-11-10",
    status: "Upcoming",
  },
  {
    task: "Check medication stock",
    description: "Ensure all essential medicines are in adequate supply.",
    category: "Inventory",
    from: "Anna Lee",
    to: "Dr. Roberts",
    toLabel: "Companions",
    due: "2025-11-09",
    status: "Completed",
  },
  {
    task: "Design promotional banner",
    description: "Create social media banner for the new wellness campaign.",
    category: "Marketing",
    from: "Rachel Green",
    to: "Healthy Paws Veterinary",
    toLabel: "Organisations",
    due: "2025-11-12",
    status: "Completed",
  },
];