import { Express } from "express";
import organizationRounter from "./organization.router";
import companionRouter from "./companion.router";
import parentRouter from "./parent.router";
import userOrganizationRouter from "./user-organization.router";
import userRouter from "./user.router";
import userProfileRouter from "./user-profile.router";
import availabilityRouter from "./availability.router";
import specialtyRouter from "./speciality.router";
import organisationRoomRouter from "./organisation-room.router";
import organisationInviteRouter from "./organisation-invite.router";
import authUserMobileRouter from "./authUserMobile.router";
import coParentInviteRouter from "./coparentInvite.router";
import parentCompanionRouter from "./parent-companion.router";
import companionOrganisationRouter from "./companion-organisation.router";
import docuemntRouter from "./document.router";
import serviceRouter from "./service.router";
import appointmentRouter from "./appointment.router";
import stripeRouter from "./stripe.router";
import financeRouter from "./finance.router";
import documensoRouter from "./documenso.router";
import ratingRouter from "./organisationRating.router";
import formRouter from "./form.router";
import formAssignmentRouter from "./form-assignment.router";
import templateRouter from "./template.router";
import templateFhirRouter from "./template.fhir.router";
import renderedDocumentFhirRouter from "./rendered-document.fhir.router";
import clinicalArtifactFhirRouter from "./clinical-artifact.fhir.router";
import prescriptionRouter from "./prescription.router";
import expenseRouter from "./expense.router";
import deviceTokenRouter from "./deviceToken.router";
import chatRouter from "./chat.router";
import notificationRouter from "./notification.router";
import contactRouter from "./contact-us.router";
import accountWithdrawalRouter from "./account-withdrawal.router";
import organisationDocumentRouter from "./organisation-document.router";
import adverseEventRouter from "./adverse-event.router";
import taskRouter from "./task.router";
import taskFhirRouter from "./task.fhir.router";
import taskScheduleFhirRouter from "./task-schedule.fhir.router";
import workspaceRouter from "./workspace.router";
import inventoryRoter from "./inventory.router";
import searchRouter from "./search.router";
import observationToolRouter from "./observationTool.routes";
import dashboardRouter from "./dashboard.router";
import mobileConfigRouter from "./mobile.config.router";
import auditTrailRouter from "./audit-trail.router";
import integrationRouter from "./integration.router";
import knowledgeRouter from "./knowledge.router";
import codeRouter from "./code.router";
import labOrderRouter from "./lab-order.router";
import labResultRouter from "./lab-result.router";
import companionHistoryRouter from "./companion-history.router";
import authRouter from "./auth.router";
import catalogRouter from "./catalog.router";
import healthcareServiceRouter from "./healthcare-service.router";
import episodeOfCareRouter from "./episode-of-care.router";
import encounterRouter from "./encounter.router";
import roomUnitRouter from "./room-unit.router";
import roomUnitGroupRouter from "./room-unit-group.router";

export function registerRoutes(app: Express) {
  app.use(`/fhir/v1/organization`, organizationRounter);
  app.use(`/fhir/v1/companion`, companionRouter);
  app.use(`/fhir/v1/parent`, parentRouter);
  app.use(`/fhir/v1/user-organization`, userOrganizationRouter);
  app.use(`/fhir/v1/user`, userRouter);
  app.use(`/fhir/v1/user-profile`, userProfileRouter);
  app.use(`/fhir/v1/speciality`, specialtyRouter);
  app.use(`/fhir/v1/organisation-room`, organisationRoomRouter);
  app.use(`/fhir/v1/room-unit`, roomUnitRouter);
  app.use(`/fhir/v1/room-unit-group`, roomUnitGroupRouter);
  app.use(`/fhir/v1/organisation-invites`, organisationInviteRouter);
  app.use(`/fhir/v1/availability`, availabilityRouter);
  app.use(`/v1/authUser`, authUserMobileRouter);
  app.use(`/v1/coparent-invite`, coParentInviteRouter);
  app.use(`/v1/parent-companion`, parentCompanionRouter);
  app.use(`/v1/companion-organisation`, companionOrganisationRouter);
  app.use(`/v1/document`, docuemntRouter);
  app.use(`/fhir/v1/service`, serviceRouter);
  app.use(`/fhir/v1/healthcare-service`, healthcareServiceRouter);
  app.use(`/fhir/v1/appointment`, appointmentRouter);
  app.use(`/fhir/v1/episode-of-care`, episodeOfCareRouter);
  app.use(`/fhir/v1/encounter`, encounterRouter);
  app.use(`/v1/stripe`, stripeRouter);
  app.use(`/v1/finance`, financeRouter);
  app.use(`/v1/documenso`, documensoRouter);
  app.use(`/v1/organisation-rating`, ratingRouter);
  app.use(`/fhir/v1/invoice`, financeRouter);
  app.use(`/fhir/v1/form`, formRouter);
  app.use(`/v1/forms`, formAssignmentRouter);
  app.use(`/fhir/v1/template`, templateFhirRouter);
  app.use(`/fhir/v1/rendered-document`, renderedDocumentFhirRouter);
  app.use(`/fhir/v1/task`, taskFhirRouter);
  app.use(`/fhir/v1/clinical-artifact`, clinicalArtifactFhirRouter);
  app.use(`/fhir/v1/task-schedule`, taskScheduleFhirRouter);
  app.use(`/v1/templates`, templateRouter);
  app.use(`/v1/workspace`, workspaceRouter);
  app.use(`/v1/prescriptions`, prescriptionRouter);
  app.use(`/v1/search`, searchRouter);
  app.use(`/v1/expense`, expenseRouter);
  app.use(`/v1/device-token`, deviceTokenRouter);
  app.use(`/v1/chat`, chatRouter);
  app.use(`/v1/notification`, notificationRouter);
  app.use(`/v1/contact-us`, contactRouter);
  app.use(`/v1/account-withdrawal`, accountWithdrawalRouter);
  app.use(`/v1/organisation-document`, organisationDocumentRouter);
  app.use(`/v1/adverse-event`, adverseEventRouter);
  app.use(`/v1/task`, taskRouter);
  app.use(`/v1/inventory`, inventoryRoter);
  app.use(`/v1/observation-tools`, observationToolRouter);
  app.use(`/v1/dashboard`, dashboardRouter);
  app.use(`/v1/mobile-config`, mobileConfigRouter);
  app.use(`/v1/audit-trail`, auditTrailRouter);
  app.use(`/v1/companion-history`, companionHistoryRouter);
  app.use(`/v1/integration`, integrationRouter);
  app.use(`/v1/knowledge`, knowledgeRouter);
  app.use(`/v1/codes`, codeRouter);
  app.use(`/v1/labs`, labOrderRouter);
  app.use(`/v1/labs`, labResultRouter);
  app.use(`/v1/auth`, authRouter);
  app.use(`/v1/catalog`, catalogRouter);
}
