import { Express } from "express";
import organizationRounter from "./organization.router";
import companionRouter from "./companion.router";
import parentRouter from "./parent.router";
import userOrganizationRouter from "./user-organization.router";
import userRouter from "./user.router";
import userProfileRouter from "./user-profile.router";
import availabilityRouter from "./availability.router";
import specialtyRouter from "./speciality.router";
import organisationRoomRouter from "./organisation-room.router";
import organisationInviteRouter from "./organisation-invite.router";
import authUserMobileRouter from "./authUserMobile.router";
import coParentInviteRouter from "./coparentInvite.router";
import parentCompanionRouter from "./parent-companion.router";
import companionOrganisationRouter from "./companion-organisation.router";
import docuemntRouter from "./document.router";
import serviceRouter from "./service.router";
import appointmentRouter from "./appointment.router";
import stripeRouter from "./stripe.router";
import ratingRouter from "./organisationRating.router";
import invoiceRouter from "./invoice.router";
import formRouter from "./form.router";
import expenseRouter from "./expense.router";
import deviceTokenRouter from "./deviceToken.router";
import chatRouter from "./chat.router";
import notificationRouter from "./notification.router";
import contactRouter from "./contact-us.router";
import accountWithdrawalRouter from "./account-withdrawal.router";
import organisationDocumentRouter from "./organisation-document.router";
import adverseEventRouter from "./adverse-event.router";
import taskRouter from "./task.router";
import inventoryRoter from "./inventory.router";
import observationToolRouter from "./observationTool.routes";

export function registerRoutes(app: Express) {
  app.use(`/fhir/v1/organization`, organizationRounter);
  app.use(`/fhir/v1/companion`, companionRouter);
  app.use(`/fhir/v1/parent`, parentRouter);
  app.use(`/fhir/v1/user-organization`, userOrganizationRouter);
  app.use(`/fhir/v1/user`, userRouter);
  app.use(`/fhir/v1/user-profile`, userProfileRouter);
  app.use(`/fhir/v1/speciality`, specialtyRouter);
  app.use(`/fhir/v1/organisation-room`, organisationRoomRouter);
  app.use(`/fhir/v1/organisation-invites`, organisationInviteRouter);
  app.use(`/fhir/v1/availability`, availabilityRouter);
  app.use(`/v1/authUser`, authUserMobileRouter);
  app.use(`/v1/coparent-invite`, coParentInviteRouter);
  app.use(`/v1/parent-companion`, parentCompanionRouter);
  app.use(`/v1/companion-organisation`, companionOrganisationRouter);
  app.use(`/v1/document`, docuemntRouter);
  app.use(`/fhir/v1/service`, serviceRouter);
  app.use(`/fhir/v1/appointment`, appointmentRouter);
  app.use(`/v1/stripe`, stripeRouter);
  app.use(`/v1/organisation-rating`, ratingRouter);
  app.use(`/fhir/v1/invoice`, invoiceRouter);
  app.use(`/fhir/v1/form`, formRouter);
  app.use(`/v1/expense`, expenseRouter);
  app.use(`/v1/device-token`, deviceTokenRouter);
  app.use(`/v1/chat`, chatRouter);
  app.use(`/v1/notification`, notificationRouter);
  app.use(`/v1/contact-us`, contactRouter);
  app.use(`/v1/account-withdrawal`, accountWithdrawalRouter);
  app.use(`/v1/organisation-document`, organisationDocumentRouter);
  app.use(`/v1/adverse-event`, adverseEventRouter);
  app.use(`/v1/task`, taskRouter);
  app.use(`/v1/inventory`, inventoryRoter);
  app.use(`/v1/observation-tools`, observationToolRouter);
}
