ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'ENCOUNTER';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ENCOUNTER_DISCHARGE_OVERRIDDEN';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ENCOUNTER_DISCHARGED';
