import type {
  AppointmentEncounter,
  CompanionAlert,
  DiagnosticOrder,
  DiagnosticTestCard,
  EncounterMode,
  InvoiceLineItem,
  LineItem,
  ObservationToolDefinition,
  PastInvoice,
  PrescriptionItem,
  ScheduleTask,
  SoapTemplate,
  WorkspaceDocument,
  WorkspaceStep,
} from '@/app/features/appointments/types/workspace';

const EMPTY_STEP_STATUS: Record<WorkspaceStep, 'EMPTY'> = {
  SOAP: 'EMPTY',
  DIAGNOSTICS: 'EMPTY',
  TREATMENT: 'EMPTY',
  INVOICE: 'EMPTY',
  SUMMARY: 'EMPTY',
};

export const OBSERVATION_TOOLS: ObservationToolDefinition[] = [
  {
    key: 'FGS',
    name: 'Feline grimace scale',
    intro:
      'The Feline Grimace Scale (FGS) (© Université de Montréal 2019) is a valid, fast, reliable and easy-to-use tool that can help with pain assessment in cats. The FGS Scale can help veterinary surgeons with clinical decisions in pain management, and determine if the administration of analgesics (i.e. pain killers) is required.',
  },
  {
    key: 'CSU_CAP',
    name: 'Canine acute pain scale',
    intro:
      'The Colorado State University Canine Acute Pain Scale (CSU-CAP) (© 2006/PW Hellyer, SR Uhrig, NG Robinson) is a simple to use tool for the assessment and monitoring of acute pain in dogs. The CSU-CAP helps veterinary professionals with clinical decisions in pain management and to determine if the administration of analgesics is required.',
  },
];

const MOCK_ALERTS: CompanionAlert[] = [
  { id: 'al-1', label: 'Needs muzzle', severity: 'CAUTION' },
  { id: 'al-2', label: 'Sensitive coat', severity: 'MEDICAL' },
  { id: 'al-3', label: 'Not friendly with Males', severity: 'INFO' },
];

const MOCK_SOAP_TEMPLATES: SoapTemplate[] = [
  { id: 'tpl-default', name: 'Default SOAP', isDefault: true },
  { id: 'tpl-ortho', name: 'Orthopaedic exam', serviceId: 'svc-ortho' },
  { id: 'tpl-derm', name: 'Dermatology workup', serviceId: 'svc-derm' },
];

const MOCK_DIAGNOSTIC_TESTS: DiagnosticTestCard[] = [
  {
    id: 'dx-1',
    name: 'Canine Senior Screen with Heartworm Antibody and Urine Culture',
    priceCents: 15000,
    currency: 'USD',
    orderCode: '23299999',
    turnaround:
      '2-5 days if culture positive, 1-2 days for negative culture results; preliminary results ..',
    specimen: '2 mL serum, 1 mL LTT, 5 mL urine in a sterile container (cystocentesis preferred)',
  },
];

const MOCK_DIAGNOSTIC_ORDERS: DiagnosticOrder[] = [
  { id: 'ord-1', orderCode: '100358709', createdAt: '2026-04-20T12:00:00Z', status: 'CREATED' },
  { id: 'ord-2', orderCode: '100358709', createdAt: '2026-04-20T12:00:00Z', status: 'SUBMITTED' },
  {
    id: 'ord-3',
    orderCode: '100358709',
    createdAt: '2026-04-20T12:00:00Z',
    status: 'COMPLETED',
    results: [
      {
        test: '17-OH Progesterone - Pre ACTH',
        value: '0.45 ng/mL',
        reference: '0.25 ng/mL',
        meter: 'N/A',
      },
      {
        test: '17-OH Progesterone - Pre ACTH',
        value: '0.45 ng/mL',
        reference: '0.25 ng/mL',
        meter: 'N/A',
      },
    ],
  },
];

const MOCK_SERVICES: LineItem[] = [
  {
    id: 'li-1',
    refId: 'svc-cerenia',
    kind: 'PACKAGE',
    name: 'SC Injection - Cerenia 0.5ml',
    qty: 1,
    instructions: "Don't give bath for 2 days, wash wound post",
    unitPriceCents: 10000,
    amountCents: 10000,
    breakdown: [
      { id: 'bd-1', name: 'Syringe', qty: 2, instructions: '-', amountCents: 1500 },
      {
        id: 'bd-2',
        name: 'Cerenia (injectable medicine)',
        qty: 1,
        instructions: '-',
        amountCents: 4500,
      },
      {
        id: 'bd-3',
        name: 'SC Injection administering charges',
        qty: 1,
        instructions: '-',
        amountCents: 4000,
      },
    ],
  },
  {
    id: 'li-2',
    refId: 'svc-acupuncture',
    kind: 'SERVICE',
    name: 'Acupuncture',
    qty: 1,
    instructions: '-',
    unitPriceCents: 13500,
    amountCents: 13500,
  },
];

const MOCK_PRESCRIPTION: PrescriptionItem[] = [
  {
    id: 'rx-1',
    medicineName: 'Amoxicillin',
    dosage: '100mg',
    route: 'Oral',
    frequency: 'BID',
    durationDays: '7 days',
    instructions: 'Finish the entire course',
    fulfillment: 'IN_HOUSE',
  },
  {
    id: 'rx-2',
    medicineName: 'Prednisone',
    dosage: '10mg',
    route: 'Oral',
    frequency: 'QD',
    durationDays: '5 days',
    instructions: 'Morning with food',
    fulfillment: 'IN_HOUSE',
  },
  {
    id: 'rx-3',
    medicineName: 'Metronidazole',
    dosage: '250mg',
    route: 'Oral',
    frequency: 'TID',
    durationDays: '10 days',
    instructions: '-',
    fulfillment: 'IN_HOUSE',
  },
];

const MOCK_SCHEDULE: ScheduleTask[] = [
  {
    id: 'sch-1',
    time: '10:00 AM',
    description: 'Record observation for analgesic',
    category: 'Record',
    assignedToName: 'Sarah Mitchell',
    status: 'COMPLETED',
    autoGenerated: true,
  },
  {
    id: 'sch-2',
    time: '12:00 PM',
    description: 'Send client estimate',
    category: 'Billing',
    assignedToName: 'Sarah Mitchell',
    status: 'UPCOMING',
    autoGenerated: false,
  },
  {
    id: 'sch-3',
    time: '12:00 PM',
    description: 'Feed patient meal',
    category: 'Care',
    assignedToName: 'Sarah Mitchell',
    status: 'CANCELLED',
    autoGenerated: false,
  },
  {
    id: 'sch-4',
    time: '2:00 PM',
    description: 'Record 2 pm vitals',
    category: 'Record',
    assignedToName: 'Sarah Mitchell',
    status: 'UPCOMING',
    startDate: '2026-04-25',
    endDate: '2026-04-30',
    autoGenerated: true,
  },
];

const MOCK_INVOICE_ITEMS: InvoiceLineItem[] = [
  {
    id: 'inv-1',
    name: 'Initial Consultation',
    unitPriceCents: 10000,
    qty: 1,
    grossCents: 10000,
    discountCents: 1000,
    amountCents: 9000,
  },
  {
    id: 'inv-2',
    name: 'Lab Test',
    unitPriceCents: 10000,
    qty: 1,
    grossCents: 10000,
    discountCents: 1000,
    amountCents: 9000,
  },
  {
    id: 'inv-3',
    name: 'X-Ray Imaging',
    unitPriceCents: 20000,
    qty: 1,
    grossCents: 20000,
    discountCents: 2000,
    amountCents: 18000,
  },
  {
    id: 'inv-4',
    name: 'Consultation Fee',
    unitPriceCents: 15000,
    qty: 1,
    grossCents: 15000,
    discountCents: 1500,
    amountCents: 13500,
  },
  {
    id: 'inv-5',
    name: 'Medication (Antibiotics)',
    unitPriceCents: 5000,
    qty: 2,
    grossCents: 10000,
    discountCents: 500,
    amountCents: 9500,
  },
  {
    id: 'inv-6',
    name: 'Lab Test',
    unitPriceCents: 10000,
    qty: 1,
    grossCents: 10000,
    discountCents: 1000,
    amountCents: 9000,
  },
  {
    id: 'inv-7',
    name: 'Physical Therapy Session',
    unitPriceCents: 7500,
    qty: 3,
    grossCents: 22500,
    discountCents: 2250,
    amountCents: 20250,
  },
];

const MOCK_PAST_INVOICES: PastInvoice[] = [
  {
    id: '20560DTH',
    createdAt: '2026-04-20T12:00:00Z',
    totalCents: 41500,
    outstandingCents: 0,
    status: 'PAID_FULL',
    byName: 'Rachel Sanders',
    items: [
      {
        id: 'pi-1',
        name: 'Initial Consultation',
        unitPriceCents: 10000,
        qty: 1,
        grossCents: 10000,
        discountCents: 1000,
        amountCents: 10000,
      },
      {
        id: 'pi-2',
        name: 'Follow-up Session',
        unitPriceCents: 7500,
        qty: 2,
        grossCents: 15000,
        discountCents: 1500,
        amountCents: 13500,
      },
      {
        id: 'pi-3',
        name: 'Comprehensive Report',
        unitPriceCents: 20000,
        qty: 1,
        grossCents: 20000,
        discountCents: 2000,
        amountCents: 18000,
      },
    ],
  },
];

const MOCK_DOCUMENTS: WorkspaceDocument[] = [
  {
    id: 'doc-soap-1',
    createdAt: '2026-04-20T12:30:00Z',
    category: 'SOAP',
    description: 'Signed SOAP note',
    signedByName: 'Dr. Tim Apple',
    lastModifiedAt: '2026-04-20T12:45:00Z',
  },
  {
    id: 'doc-invoice-1',
    createdAt: '2026-04-20T13:10:00Z',
    category: 'Invoice',
    description: 'Paid invoice 20560DTH',
    signedByName: 'Rachel Sanders',
    lastModifiedAt: '2026-04-20T13:15:00Z',
  },
  {
    id: 'doc-discharge-draft',
    createdAt: '2026-04-20T14:00:00Z',
    category: 'Discharge',
    description: 'Discharge instructions draft',
    lastModifiedAt: '2026-04-20T14:00:00Z',
    signatureRequired: true,
  },
];

/** Build a fresh, complete mock encounter for the given appointment + mode. */
export const buildMockEncounter = (
  appointmentId: string,
  mode: EncounterMode
): AppointmentEncounter => ({
  appointmentId,
  mode,
  consultationType: mode === 'INPATIENT' ? 'Inpatient' : 'Outpatient',
  leadId: 'usr-tim',
  leadName: 'Dr. Tim Apple',
  nurseId: 'usr-sarah',
  nurseName: 'Sarah Mitchell',
  alerts: MOCK_ALERTS.map((a) => ({ ...a })),
  soap: [],
  soapTemplates: MOCK_SOAP_TEMPLATES.map((t) => ({ ...t })),
  vitals: [],
  observations: [],
  diagnosticTests: MOCK_DIAGNOSTIC_TESTS.map((t) => ({ ...t })),
  diagnosticOrders: MOCK_DIAGNOSTIC_ORDERS.map((o) => ({ ...o })),
  services: MOCK_SERVICES.map((s) => ({ ...s })),
  prescription: MOCK_PRESCRIPTION.map((p) => ({ ...p })),
  schedule: mode === 'INPATIENT' ? MOCK_SCHEDULE.map((s) => ({ ...s })) : [],
  roomId: mode === 'INPATIENT' ? 'room-1' : undefined,
  unitId: mode === 'INPATIENT' ? 'unit-24' : undefined,
  invoiceLineItems: MOCK_INVOICE_ITEMS.map((i) => ({ ...i })),
  pastInvoices: MOCK_PAST_INVOICES.map((i) => ({ ...i, items: i.items.map((it) => ({ ...it })) })),
  depositCents: 120000,
  withdrawDeposit: false,
  taxPercent: 7,
  overallDiscountPercent: 5,
  dischargeSummary: '',
  followUpAt: undefined,
  documents: MOCK_DOCUMENTS.map((d) => ({ ...d })),
  readyForBilling: { value: false },
  readyForDischarge: { value: false },
  stepStatus: { ...EMPTY_STEP_STATUS },
  lockedAt: undefined,
  viewOnly: false,
});
