export type InventoryStatus = "Low stock" | "Expired" | "Hidden" | "This week";

export type InventoryCategory = "Medicine" | "Consumable" | "Equipment";

export interface InventoryItem {
  name: string;
  category: InventoryCategory;
  onHand: number;
  unitCost: number;
  sellingPrice: number;
  totalValue: number;
  expiry: string;
  location: string;
  status: InventoryStatus;
}

export interface InventoryTurnoverItem {
  name: string;
  category: "Medicine" | "Consumable" | "Equipment";
  beginningInventory: number;
  endingInventory: number;
  averageInventory: number;
  totalPurchases: number;
  turnsPerYear: number;
  daysOnShelf: number;
  status: "Excellent" | "Healthy" | "Moderate" | "Low" | "Out of stock";
}

export const DemoInventoryTurnover: InventoryTurnoverItem[] = [
  {
    name: "Paracetamol 500mg",
    category: "Medicine",
    beginningInventory: 200,
    endingInventory: 80,
    averageInventory: 140,
    totalPurchases: 300,
    turnsPerYear: 12,
    daysOnShelf: 30,
    status: "Excellent"
  },
  {
    name: "Surgical Gloves (Medium)",
    category: "Consumable",
    beginningInventory: 500,
    endingInventory: 300,
    averageInventory: 400,
    totalPurchases: 600,
    turnsPerYear: 8,
    daysOnShelf: 45,
    status: "Healthy"
  },
  {
    name: "Syringe 5ml",
    category: "Consumable",
    beginningInventory: 800,
    endingInventory: 600,
    averageInventory: 700,
    totalPurchases: 1000,
    turnsPerYear: 6,
    daysOnShelf: 60,
    status: "Moderate"
  },
  {
    name: "Blood Pressure Monitor",
    category: "Equipment",
    beginningInventory: 20,
    endingInventory: 15,
    averageInventory: 17.5,
    totalPurchases: 10,
    turnsPerYear: 2,
    daysOnShelf: 180,
    status: "Low"
  },
  {
    name: "Vitamin C Tablets",
    category: "Medicine",
    beginningInventory: 300,
    endingInventory: 120,
    averageInventory: 210,
    totalPurchases: 350,
    turnsPerYear: 10,
    daysOnShelf: 36,
    status: "Excellent"
  },
  {
    name: "Face Masks",
    category: "Consumable",
    beginningInventory: 1000,
    endingInventory: 200,
    averageInventory: 600,
    totalPurchases: 1500,
    turnsPerYear: 15,
    daysOnShelf: 24,
    status: "Excellent"
  },
  {
    name: "Wheelchair",
    category: "Equipment",
    beginningInventory: 12,
    endingInventory: 10,
    averageInventory: 11,
    totalPurchases: 5,
    turnsPerYear: 1,
    daysOnShelf: 365,
    status: "Low"
  },
  {
    name: "Amoxicillin 250mg",
    category: "Medicine",
    beginningInventory: 150,
    endingInventory: 40,
    averageInventory: 95,
    totalPurchases: 200,
    turnsPerYear: 11,
    daysOnShelf: 33,
    status: "Healthy"
  },
  {
    name: "Hand Sanitizer 500ml",
    category: "Consumable",
    beginningInventory: 300,
    endingInventory: 50,
    averageInventory: 175,
    totalPurchases: 400,
    turnsPerYear: 14,
    daysOnShelf: 26,
    status: "Excellent"
  },
  {
    name: "Nebulizer Machine",
    category: "Equipment",
    beginningInventory: 10,
    endingInventory: 0,
    averageInventory: 5,
    totalPurchases: 8,
    turnsPerYear: 3,
    daysOnShelf: 120,
    status: "Out of stock"
  }
];

export const InventoryData: InventoryItem[] = [
  {
    name: "Zinc Supplement 50mg",
    category: "Medicine",
    onHand: 130,
    unitCost: 2,
    sellingPrice: 4,
    totalValue: 130 * 2,
    expiry: "2026-11-10",
    location: "Shelf A10",
    status: "This week",
  },
  {
    name: "Disposable Shoe Covers (Pack of 50)",
    category: "Consumable",
    onHand: 75,
    unitCost: 30,
    sellingPrice: 50,
    totalValue: 75 * 30,
    expiry: "2027-03-05",
    location: "Shelf E1",
    status: "This week",
  },
  {
    name: "Blood Pressure Monitor",
    category: "Equipment",
    onHand: 15,
    unitCost: 1200,
    sellingPrice: 1700,
    totalValue: 15 * 1200,
    expiry: "2030-06-18",
    location: "Equipment Room 8",
    status: "This week",
  },
  {
    name: "Hydrogen Peroxide 3%",
    category: "Consumable",
    onHand: 55,
    unitCost: 12,
    sellingPrice: 20,
    totalValue: 55 * 12,
    expiry: "2026-09-22",
    location: "Shelf E2",
    status: "This week",
  },
  {
    name: "Cefixime 200mg Tablets",
    category: "Medicine",
    onHand: 90,
    unitCost: 9,
    sellingPrice: 15,
    totalValue: 90 * 9,
    expiry: "2027-08-14",
    location: "Shelf A11",
    status: "This week",
  },
  {
    name: "Surgical Face Masks (Box of 50)",
    category: "Consumable",
    onHand: 200,
    unitCost: 40,
    sellingPrice: 60,
    totalValue: 200 * 40,
    expiry: "2028-01-01",
    location: "Shelf E3",
    status: "This week",
  },
  {
    name: "Portable Stretcher",
    category: "Equipment",
    onHand: 8,
    unitCost: 9000,
    sellingPrice: 12000,
    totalValue: 8 * 9000,
    expiry: "2032-12-01",
    location: "Emergency Storage",
    status: "This week",
  },
  {
    name: "Oral Rehydration Salts (ORS)",
    category: "Consumable",
    onHand: 340,
    unitCost: 1,
    sellingPrice: 2,
    totalValue: 340 * 1,
    expiry: "2026-07-15",
    location: "Shelf E4",
    status: "This week",
  },
  {
    name: "Glucose Meter Test Strips",
    category: "Consumable",
    onHand: 180,
    unitCost: 10,
    sellingPrice: 18,
    totalValue: 180 * 10,
    expiry: "2026-12-30",
    location: "Shelf E5",
    status: "This week",
  },
  {
    name: "Heparin Injection 5ml",
    category: "Medicine",
    onHand: 60,
    unitCost: 18,
    sellingPrice: 25,
    totalValue: 60 * 18,
    expiry: "2025-11-02",
    location: "Refrigerator 2",
    status: "This week",
  },
  {
    name: "Paracetamol 500mg",
    category: "Medicine",
    onHand: 120,
    unitCost: 3,
    sellingPrice: 5,
    totalValue: 120 * 3,
    expiry: "2026-03-15",
    location: "Shelf A1",
    status: "Low stock",
  },
  {
    name: "Ibuprofen 200mg",
    category: "Medicine",
    onHand: 80,
    unitCost: 4,
    sellingPrice: 7,
    totalValue: 80 * 4,
    expiry: "2027-07-21",
    location: "Shelf A2",
    status: "Hidden",
  },
  {
    name: "Insulin Vials",
    category: "Medicine",
    onHand: 10,
    unitCost: 200,
    sellingPrice: 280,
    totalValue: 10 * 200,
    expiry: "2024-12-10",
    location: "Refrigerator",
    status: "Expired",
  },
  {
    name: "Vitamin C Tablets",
    category: "Medicine",
    onHand: 200,
    unitCost: 1.5,
    sellingPrice: 3,
    totalValue: 200 * 1.5,
    expiry: "2025-11-03",
    location: "Shelf A3",
    status: "Hidden",
  },
  {
    name: "Antibiotic Ointment",
    category: "Medicine",
    onHand: 50,
    unitCost: 12,
    sellingPrice: 20,
    totalValue: 50 * 12,
    expiry: "2026-08-14",
    location: "Shelf A4",
    status: "Low stock",
  },

  // Consumables
  {
    name: "N95 Masks (Pack of 10)",
    category: "Consumable",
    onHand: 45,
    unitCost: 50,
    sellingPrice: 80,
    totalValue: 45 * 50,
    expiry: "2027-01-01",
    location: "Shelf B1",
    status: "Hidden",
  },
  {
    name: "Surgical Gloves (Box of 100)",
    category: "Consumable",
    onHand: 90,
    unitCost: 75,
    sellingPrice: 110,
    totalValue: 90 * 75,
    expiry: "2028-04-10",
    location: "Shelf B2",
    status: "Low stock",
  },
  {
    name: "Disposable Syringes 5ml",
    category: "Consumable",
    onHand: 300,
    unitCost: 2,
    sellingPrice: 4,
    totalValue: 300 * 2,
    expiry: "2028-06-20",
    location: "Shelf B3",
    status: "Hidden",
  },
  {
    name: "Alcohol Swabs",
    category: "Consumable",
    onHand: 500,
    unitCost: 0.5,
    sellingPrice: 1,
    totalValue: 500 * 0.5,
    expiry: "2027-02-05",
    location: "Shelf B4",
    status: "Hidden",
  },
  {
    name: "IV Fluid Bag 500ml",
    category: "Consumable",
    onHand: 65,
    unitCost: 30,
    sellingPrice: 45,
    totalValue: 65 * 30,
    expiry: "2025-09-12",
    location: "Shelf B5",
    status: "Low stock",
  },

  // Equipment
  {
    name: "ECG Machine – Model X200",
    category: "Equipment",
    onHand: 5,
    unitCost: 25000,
    sellingPrice: 30000,
    totalValue: 5 * 25000,
    expiry: "2030-12-31",
    location: "Equipment Room 1",
    status: "Low stock",
  },
  {
    name: "Wheelchair - Standard",
    category: "Equipment",
    onHand: 12,
    unitCost: 6000,
    sellingPrice: 7500,
    totalValue: 12 * 6000,
    expiry: "2032-01-01",
    location: "Equipment Room 2",
    status: "Hidden",
  },
  {
    name: "Pulse Oximeter",
    category: "Equipment",
    onHand: 20,
    unitCost: 800,
    sellingPrice: 1200,
    totalValue: 20 * 800,
    expiry: "2031-05-19",
    location: "Equipment Room 3",
    status: "Low stock",
  },
  {
    name: "Defibrillator – AED Pro",
    category: "Equipment",
    onHand: 3,
    unitCost: 45000,
    sellingPrice: 52000,
    totalValue: 3 * 45000,
    expiry: "2033-04-01",
    location: "Emergency Ward",
    status: "Low stock",
  },
  {
    name: "Ultrasound Scanner – MiniScan",
    category: "Equipment",
    onHand: 2,
    unitCost: 70000,
    sellingPrice: 85000,
    totalValue: 2 * 70000,
    expiry: "2034-11-22",
    location: "Radiology",
    status: "Hidden",
  },

  // More Medicines
  {
    name: "Aspirin 81mg",
    category: "Medicine",
    onHand: 150,
    unitCost: 2,
    sellingPrice: 4,
    totalValue: 150 * 2,
    expiry: "2026-01-30",
    location: "Shelf A5",
    status: "Hidden",
  },
  {
    name: "Cough Syrup",
    category: "Medicine",
    onHand: 35,
    unitCost: 18,
    sellingPrice: 28,
    totalValue: 35 * 18,
    expiry: "2025-04-19",
    location: "Shelf A6",
    status: "Low stock",
  },
  {
    name: "Antacid Tablets",
    category: "Medicine",
    onHand: 250,
    unitCost: 1,
    sellingPrice: 2,
    totalValue: 250 * 1,
    expiry: "2027-08-08",
    location: "Shelf A7",
    status: "Hidden",
  },

  // More Consumables
  {
    name: "Blood Collection Tubes",
    category: "Consumable",
    onHand: 400,
    unitCost: 3,
    sellingPrice: 5,
    totalValue: 400 * 3,
    expiry: "2029-10-11",
    location: "Lab Storage",
    status: "Hidden",
  },
  {
    name: "Surgical Drapes",
    category: "Consumable",
    onHand: 70,
    unitCost: 20,
    sellingPrice: 35,
    totalValue: 70 * 20,
    expiry: "2026-12-17",
    location: "OR Supply Area",
    status: "Low stock",
  },
  {
    name: "Sterile Water 100ml",
    category: "Consumable",
    onHand: 110,
    unitCost: 6,
    sellingPrice: 10,
    totalValue: 110 * 6,
    expiry: "2025-07-22",
    location: "Shelf C1",
    status: "Low stock",
  },

  // More Equipment
  {
    name: "Hospital Bed – Hydraulic",
    category: "Equipment",
    onHand: 7,
    unitCost: 32000,
    sellingPrice: 38000,
    totalValue: 7 * 32000,
    expiry: "2035-09-09",
    location: "Ward Storage",
    status: "Hidden",
  },
  {
    name: "Oxygen Concentrator",
    category: "Equipment",
    onHand: 9,
    unitCost: 15000,
    sellingPrice: 18000,
    totalValue: 9 * 15000,
    expiry: "2033-03-05",
    location: "Equipment Room 4",
    status: "Low stock",
  },
  {
    name: "Nebulizer Machine",
    category: "Equipment",
    onHand: 25,
    unitCost: 2000,
    sellingPrice: 2600,
    totalValue: 25 * 2000,
    expiry: "2032-06-14",
    location: "Equipment Room 5",
    status: "Hidden",
  },
];
