import React, { useMemo, useState } from 'react';
import {
  LuArrowRight,
  LuCalendarClock,
  LuEye,
  LuFilter,
  LuPlus,
  LuRefreshCw,
  LuSearch,
} from 'react-icons/lu';
import SectionContainer from '@/app/ui/primitives/SectionContainer/SectionContainer';
import Search from '@/app/ui/inputs/Search';
import LabelDropdown from '@/app/ui/inputs/Dropdown/LabelDropdown';
import { Primary, Secondary } from '@/app/ui/primitives/Buttons';
import CircleIconButton from '@/app/features/appointments/pages/AppointmentWorkspace/components/CircleIconButton';
import type { ScheduleTask, ScheduleTaskStatus } from '@/app/features/appointments/types/workspace';

type InpatientScheduleProps = {
  tasks: ScheduleTask[];
  readOnly: boolean;
  onAddTask: (task: Omit<ScheduleTask, 'id'>) => void;
  onUpdateTask: (id: string, patch: Partial<ScheduleTask>) => void;
};

const STATUS_CLASSES: Record<ScheduleTaskStatus, string> = {
  COMPLETED: 'border-pill-success-border bg-pill-success-bg text-pill-success-text',
  UPCOMING: 'border-pill-info-border bg-pill-info-bg text-pill-info-text',
  CANCELLED: 'border-pill-warning-border bg-pill-warning-bg text-pill-warning-text',
  PENDING: 'border-pill-neutral-border bg-pill-neutral-bg text-pill-neutral-text',
};

const STATUS_OPTIONS: { label: string; value: ScheduleTaskStatus }[] = [
  { label: 'Upcoming', value: 'UPCOMING' },
  { label: 'Completed', value: 'COMPLETED' },
  { label: 'Cancelled', value: 'CANCELLED' },
  { label: 'Pending', value: 'PENDING' },
];

const ASSIGNEE_OPTIONS = [
  { label: 'Sarah Mitchell', value: 'usr-sarah' },
  { label: 'Dr. Tim Apple', value: 'usr-tim' },
];

const formatStatusLabel = (status: ScheduleTaskStatus): string =>
  STATUS_OPTIONS.find((option) => option.value === status)?.label ?? status;

const StatusPill = ({ status }: { status: ScheduleTaskStatus }) => (
  <span
    className={`inline-flex rounded-2xl border px-3 py-1 text-caption-1 ${STATUS_CLASSES[status]}`}
  >
    {formatStatusLabel(status)}
  </span>
);

/** Vertical timeline marker: outer ring + solid centre dot (matches the stepper). */
const TimelineMarker = ({ active }: { active: boolean }) => {
  const ring = active ? 'border-text-brand' : 'border-neutral-300';
  const dot = active ? 'bg-text-brand' : 'bg-neutral-300';
  return (
    <span
      aria-hidden="true"
      className={`flex size-5 shrink-0 items-center justify-center rounded-full border-2 bg-neutral-0 ${ring}`}
    >
      <span className={`size-2 rounded-full ${dot}`} />
    </span>
  );
};

const InpatientSchedule = ({
  tasks,
  readOnly,
  onAddTask,
  onUpdateTask,
}: InpatientScheduleProps) => {
  const [search, setSearch] = useState('');
  const [expandedId, setExpandedId] = useState<string | null>(tasks[0]?.id ?? null);

  const filteredTasks = useMemo(() => {
    const query = search.trim().toLowerCase();
    if (!query) return tasks;
    return tasks.filter((task) =>
      [task.description, task.category, task.assignedToName, task.status].some((value) =>
        String(value ?? '')
          .toLowerCase()
          .includes(query)
      )
    );
  }, [search, tasks]);

  const handleAddTask = () => {
    onAddTask({
      description: 'Unassigned treatment task',
      category: 'Care',
      status: 'UPCOMING',
      autoGenerated: false,
      startDate: '2026-04-25',
      endDate: '2026-04-30',
    });
  };

  const handleToggleExpanded = (id: string) => {
    setExpandedId((current) => (current === id ? null : id));
  };

  return (
    <SectionContainer title="Schedule" className="flex flex-col gap-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3 text-body-3-emphasis text-text-primary">
          <LuCalendarClock aria-hidden="true" />
          <span>Today 24 Apr, 2026</span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <CircleIconButton
            icon={<LuPlus aria-hidden="true" />}
            label="Add schedule task"
            variant="dark"
            disabled={readOnly}
            onClick={handleAddTask}
          />
          <CircleIconButton
            icon={<LuFilter aria-hidden="true" />}
            label="Filter schedule"
            onClick={() => undefined}
          />
          <Search
            value={search}
            setSearch={setSearch}
            placeholder="Search for task"
            label="Search schedule tasks"
          />
        </div>
      </div>

      <ol className="flex flex-col">
        {filteredTasks.map((task, index) => {
          const expanded = expandedId === task.id;
          const isFirst = index === 0;
          const isLast = index === filteredTasks.length - 1;
          return (
            <li key={task.id} className="flex gap-3">
              {/* Time + vertical timeline rail (marker centred, line running through) */}
              <span className="w-20 shrink-0 pt-4 text-right text-body-4 font-medium text-pill-success-text">
                {task.time ?? '-'}
              </span>
              <div className="relative flex shrink-0 flex-col items-center">
                <span className={`h-4 w-px flex-none ${isFirst ? '' : 'bg-card-border'}`} />
                <TimelineMarker active={task.status !== 'CANCELLED'} />
                <span className={`w-px flex-1 ${isLast ? '' : 'bg-card-border'}`} />
              </div>
              <div className="mb-3 flex-1 rounded-2xl border border-card-border p-4">
                <div className="grid gap-3 text-body-4 text-text-primary lg:grid-cols-[1.4fr_120px_180px_130px_120px] lg:items-center">
                  <span>{task.description}</span>
                  <span>{task.category}</span>
                  <LabelDropdown
                    placeholder="Assigned to"
                    options={ASSIGNEE_OPTIONS}
                    defaultOption={task.assignedToId ?? task.assignedToName}
                    searchable={false}
                    onSelect={(option) =>
                      onUpdateTask(task.id, {
                        assignedToId: option.value,
                        assignedToName: option.label,
                      })
                    }
                  />
                  <LabelDropdown
                    placeholder="Status"
                    options={STATUS_OPTIONS}
                    defaultOption={task.status}
                    searchable={false}
                    onSelect={(option) =>
                      onUpdateTask(task.id, { status: option.value as ScheduleTaskStatus })
                    }
                  />
                  <div className="flex justify-end gap-2">
                    <CircleIconButton
                      icon={<LuRefreshCw aria-hidden="true" />}
                      label={`Reschedule ${task.description}`}
                      disabled={readOnly}
                      onClick={() => onUpdateTask(task.id, { time: '5:40 PM' })}
                    />
                    <CircleIconButton
                      icon={<LuEye aria-hidden="true" />}
                      label={expanded ? `Hide ${task.description}` : `View ${task.description}`}
                      variant="dark"
                      onClick={() => handleToggleExpanded(task.id)}
                    />
                  </div>
                </div>
                <div className="mt-3">
                  <StatusPill status={task.status} />
                </div>
                {expanded && (
                  <div className="mt-4 rounded-2xl bg-primary-100 p-4">
                    <div className="grid gap-3 text-body-4 text-text-primary sm:grid-cols-3">
                      <span>Starts: {task.startDate ?? 'Apr 25, 2026'}</span>
                      <span>Ends: {task.endDate ?? 'Apr 30, 2026'}</span>
                      <span>Set Time: {task.time ?? '5:40 PM'}</span>
                    </div>
                    <div className="mt-3 flex justify-end">
                      <Primary
                        text="Record"
                        icon={<LuArrowRight aria-hidden="true" />}
                        iconPosition="right"
                        onClick={() => undefined}
                        isDisabled={readOnly}
                      />
                    </div>
                  </div>
                )}
              </div>
            </li>
          );
        })}
      </ol>

      {filteredTasks.length === 0 && (
        <p className="rounded-2xl bg-neutral-100 p-4 text-body-4 text-text-secondary">
          No schedule tasks match this search.
        </p>
      )}

      <div className="flex justify-end">
        <Secondary
          text="Schedule filters"
          icon={<LuSearch aria-hidden="true" />}
          onClick={() => undefined}
        />
      </div>
    </SectionContainer>
  );
};

export default InpatientSchedule;
