ALTER TYPE "TaskKind" ADD VALUE IF NOT EXISTS 'CARE';
ALTER TYPE "TaskKind" ADD VALUE IF NOT EXISTS 'PROCEDURE';
ALTER TYPE "TaskKind" ADD VALUE IF NOT EXISTS 'DIAGNOSTIC';
ALTER TYPE "TaskKind" ADD VALUE IF NOT EXISTS 'COMMUNICATION';
ALTER TYPE "TaskKind" ADD VALUE IF NOT EXISTS 'BILLING';
ALTER TYPE "TaskKind" ADD VALUE IF NOT EXISTS 'RECORD';
ALTER TYPE "TaskKind" ADD VALUE IF NOT EXISTS 'ADMIN';
