export const publicRoutes = new Set([
  '/',
  '/signin',
  '/signup',
  '/developers/signin',
  '/developers/signup',
  '/forgot-password',
  '/about-us',
  '/pet-parents',
  '/book-demo',
  '/contact-us',
  '/developers',
  '/pet-businesses',
  '/pricing',
  '/privacy-policy',
  '/terms-and-conditions',
]);
