import { FormsProps } from "@/app/types/forms";

export const demoForms: FormsProps[] = [
  {
    name: "General Consent Form",
    description: "Standard consent required before routine procedures.",
    services: [],
    species: [],
    category: "Consent form",
    usage: "Internal & External",
    updatedBy: "Dr. Emily Carter",
    lastUpdated: "2025-01-10",
    status: "Published",
  },
  {
    name: "Surgery Consent Form",
    description: "Consent form for all surgical procedures.",
    services: [],
    species: [],
    category: "Consent form",
    usage: "External",
    updatedBy: "Dr. John Miller",
    lastUpdated: "2025-01-09",
    status: "Published",
  },
  {
    name: "Vaccination Record Form",
    description: "Captures vaccination history for all animals.",
    services: [],
    species: [],
    category: "Vaccination",
    usage: "Internal",
    updatedBy: "Nurse Sarah Blake",
    lastUpdated: "2025-01-05",
    status: "Published",
  },
  {
    name: "Discharge Summary - General",
    description: "Used for discharging patients after non-surgical visits.",
    services: [],
    species: [],
    category: "Discharge",
    usage: "Internal",
    updatedBy: "Dr. Ravi Patel",
    lastUpdated: "2025-01-08",
    status: "Draft",
  },
  {
    name: "Post-Surgery Discharge Summary",
    description: "Instructions and notes after surgery.",
    services: [],
    species: [],
    category: "Discharge",
    usage: "External",
    updatedBy: "Dr. Anna Lopez",
    lastUpdated: "2025-01-06",
    status: "Published",
  },
  {
    name: "Dermatology Medical Note",
    description: "Notes for dermatology-related cases.",
    services: [],
    species: [],
    category: "Medical note",
    usage: "Internal",
    updatedBy: "Dr. Megan Shaw",
    lastUpdated: "2025-01-03",
    status: "Draft",
  },
  {
    name: "Exotic Pet Intake Form",
    description: "Form for initial assessment of exotic species.",
    services: [],
    species: [],
    category: "Medical note",
    usage: "Internal",
    updatedBy: "Dr. Liam Turner",
    lastUpdated: "2025-01-02",
    status: "Published",
  },
  {
    name: "Dental Procedure Consent",
    description: "Consent for dental cleaning or extractions.",
    services: [],
    species: [],
    category: "Procedure",
    usage: "External",
    updatedBy: "Dr. Olivia Kim",
    lastUpdated: "2025-01-11",
    status: "Published",
  },
  {
    name: "Rabies Vaccination Certificate",
    description: "External certificate for rabies vaccination.",
    services: [],
    species: [],
    category: "Vaccination",
    usage: "External",
    updatedBy: "Nurse Daniel Brooks",
    lastUpdated: "2025-01-04",
    status: "Draft",
  },
  {
    name: "Chronic Condition Management Note",
    description: "Internal notes for long-term condition follow-ups.",
    services: [],
    species: [],
    category: "Medical note",
    usage: "Internal",
    updatedBy: "Dr. Karen Foster",
    lastUpdated: "2025-01-07",
    status: "Archived",
  },
];
