export default {
  "138e0e15": [() => import(/* webpackChunkName: "138e0e15" */ "@generated/@easyops-cn/docusaurus-search-local/default/__plugin.json"), "@generated/@easyops-cn/docusaurus-search-local/default/__plugin.json", require.resolveWeak("@generated/@easyops-cn/docusaurus-search-local/default/__plugin.json")],
  "152fb8f8": [() => import(/* webpackChunkName: "152fb8f8" */ "@site/docs/guides/notification-setup-guide.md"), "@site/docs/guides/notification-setup-guide.md", require.resolveWeak("@site/docs/guides/notification-setup-guide.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1a4e3797": [() => import(/* webpackChunkName: "1a4e3797" */ "@theme/SearchPage"), "@theme/SearchPage", require.resolveWeak("@theme/SearchPage")],
  "1db64337": [() => import(/* webpackChunkName: "1db64337" */ "@site/docs/overview.md"), "@site/docs/overview.md", require.resolveWeak("@site/docs/overview.md")],
  "35eaa0ef": [() => import(/* webpackChunkName: "35eaa0ef" */ "@site/docs/policies/code-of-conduct.md"), "@site/docs/policies/code-of-conduct.md", require.resolveWeak("@site/docs/policies/code-of-conduct.md")],
  "380e72ac": [() => import(/* webpackChunkName: "380e72ac" */ "@site/docs/policies/contributing.md"), "@site/docs/policies/contributing.md", require.resolveWeak("@site/docs/policies/contributing.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "772fc7d7": [() => import(/* webpackChunkName: "772fc7d7" */ "@site/docs/apps/frontend.md"), "@site/docs/apps/frontend.md", require.resolveWeak("@site/docs/apps/frontend.md")],
  "7d8dc131": [() => import(/* webpackChunkName: "7d8dc131" */ "@site/docs/guides/backend-chat-implementation.md"), "@site/docs/guides/backend-chat-implementation.md", require.resolveWeak("@site/docs/guides/backend-chat-implementation.md")],
  "8221ce8e": [() => import(/* webpackChunkName: "8221ce8e" */ "@generated/docusaurus-plugin-content-docs/default/p/dev-docs-0bd.json"), "@generated/docusaurus-plugin-content-docs/default/p/dev-docs-0bd.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/dev-docs-0bd.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "bbff8e77": [() => import(/* webpackChunkName: "bbff8e77" */ "@site/docs/policies/security.md"), "@site/docs/policies/security.md", require.resolveWeak("@site/docs/policies/security.md")],
  "d837a2a0": [() => import(/* webpackChunkName: "d837a2a0" */ "@site/docs/apps/mobile-app.md"), "@site/docs/apps/mobile-app.md", require.resolveWeak("@site/docs/apps/mobile-app.md")],
  "e3c9d887": [() => import(/* webpackChunkName: "e3c9d887" */ "@site/docs/apps/backend.md"), "@site/docs/apps/backend.md", require.resolveWeak("@site/docs/apps/backend.md")],};
