import { CompanionProps } from "@/app/components/DataTable/types";

export const demoData: CompanionProps[] = [
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Buddy",
    breed: "Golden Retriever",
    species: "Dog",
    parent: "Aarav Mehta",
    gender: "Male",
    age: "4 years",
    lastMedication: "Heartworm Preventive (Sep 2025)",
    vaccineDue: "Rabies (Dec 2025)",
    upcomingAppointent: "General Checkup - Nov 20, 2025",
    upcomingAppointentTime: "03:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Misty",
    breed: "Siamese",
    species: "Cat",
    parent: "Ishita Roy",
    gender: "Female",
    age: "2 years",
    lastMedication: "Flea Treatment (Oct 2025)",
    vaccineDue: "FVRCP (Nov 2025)",
    upcomingAppointent: "Dental Cleaning - Dec 3, 2025",
    upcomingAppointentTime: "09:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Rocky",
    breed: "German Shepherd",
    species: "Dog",
    parent: "Rohan Patel",
    gender: "Male",
    age: "6 years",
    lastMedication: "Arthritis Support (Aug 2025)",
    vaccineDue: "Bordetella (Jan 2026)",
    upcomingAppointent: "Vaccination - Nov 25, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Coco",
    breed: "Mini Lop",
    species: "Rabbit",
    parent: "Sneha Verma",
    gender: "Female",
    age: "1 year",
    lastMedication: "Deworming (Sep 2025)",
    vaccineDue: "Myxomatosis (Feb 2026)",
    upcomingAppointent: "Nail Trim - Nov 18, 2025",
    upcomingAppointentTime: "13:15 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Kiwi",
    breed: "Cockatiel",
    species: "Bird",
    parent: "Vikram Singh",
    gender: "Male",
    age: "3 years",
    lastMedication: "Parasite Control (Oct 2025)",
    vaccineDue: "Avian Influenza (Apr 2026)",
    upcomingAppointent: "Wing Check - Dec 10, 2025",
    upcomingAppointentTime: "23:45 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Luna",
    breed: "Beagle",
    species: "Dog",
    parent: "Ananya Gupta",
    gender: "Female",
    age: "5 years",
    lastMedication: "Tick Preventive (Oct 2025)",
    vaccineDue: "DHPP (Jan 2026)",
    upcomingAppointent: "Skin Allergy Review - Nov 29, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Buddy",
    breed: "Golden Retriever",
    species: "Dog",
    parent: "Aarav Mehta",
    gender: "Male",
    age: "4 years",
    lastMedication: "Heartworm Preventive (Sep 2025)",
    vaccineDue: "Rabies (Dec 2025)",
    upcomingAppointent: "General Checkup - Nov 20, 2025",
    upcomingAppointentTime: "03:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Misty",
    breed: "Siamese",
    species: "Cat",
    parent: "Ishita Roy",
    gender: "Female",
    age: "2 years",
    lastMedication: "Flea Treatment (Oct 2025)",
    vaccineDue: "FVRCP (Nov 2025)",
    upcomingAppointent: "Dental Cleaning - Dec 3, 2025",
    upcomingAppointentTime: "09:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Rocky",
    breed: "German Shepherd",
    species: "Dog",
    parent: "Rohan Patel",
    gender: "Male",
    age: "6 years",
    lastMedication: "Arthritis Support (Aug 2025)",
    vaccineDue: "Bordetella (Jan 2026)",
    upcomingAppointent: "Vaccination - Nov 25, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Coco",
    breed: "Mini Lop",
    species: "Rabbit",
    parent: "Sneha Verma",
    gender: "Female",
    age: "1 year",
    lastMedication: "Deworming (Sep 2025)",
    vaccineDue: "Myxomatosis (Feb 2026)",
    upcomingAppointent: "Nail Trim - Nov 18, 2025",
    upcomingAppointentTime: "13:15 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Kiwi",
    breed: "Cockatiel",
    species: "Bird",
    parent: "Vikram Singh",
    gender: "Male",
    age: "3 years",
    lastMedication: "Parasite Control (Oct 2025)",
    vaccineDue: "Avian Influenza (Apr 2026)",
    upcomingAppointent: "Wing Check - Dec 10, 2025",
    upcomingAppointentTime: "23:45 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Luna",
    breed: "Beagle",
    species: "Dog",
    parent: "Ananya Gupta",
    gender: "Female",
    age: "5 years",
    lastMedication: "Tick Preventive (Oct 2025)",
    vaccineDue: "DHPP (Jan 2026)",
    upcomingAppointent: "Skin Allergy Review - Nov 29, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Buddy",
    breed: "Golden Retriever",
    species: "Dog",
    parent: "Aarav Mehta",
    gender: "Male",
    age: "4 years",
    lastMedication: "Heartworm Preventive (Sep 2025)",
    vaccineDue: "Rabies (Dec 2025)",
    upcomingAppointent: "General Checkup - Nov 20, 2025",
    upcomingAppointentTime: "03:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Misty",
    breed: "Siamese",
    species: "Cat",
    parent: "Ishita Roy",
    gender: "Female",
    age: "2 years",
    lastMedication: "Flea Treatment (Oct 2025)",
    vaccineDue: "FVRCP (Nov 2025)",
    upcomingAppointent: "Dental Cleaning - Dec 3, 2025",
    upcomingAppointentTime: "09:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Rocky",
    breed: "German Shepherd",
    species: "Dog",
    parent: "Rohan Patel",
    gender: "Male",
    age: "6 years",
    lastMedication: "Arthritis Support (Aug 2025)",
    vaccineDue: "Bordetella (Jan 2026)",
    upcomingAppointent: "Vaccination - Nov 25, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Coco",
    breed: "Mini Lop",
    species: "Rabbit",
    parent: "Sneha Verma",
    gender: "Female",
    age: "1 year",
    lastMedication: "Deworming (Sep 2025)",
    vaccineDue: "Myxomatosis (Feb 2026)",
    upcomingAppointent: "Nail Trim - Nov 18, 2025",
    upcomingAppointentTime: "13:15 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Kiwi",
    breed: "Cockatiel",
    species: "Bird",
    parent: "Vikram Singh",
    gender: "Male",
    age: "3 years",
    lastMedication: "Parasite Control (Oct 2025)",
    vaccineDue: "Avian Influenza (Apr 2026)",
    upcomingAppointent: "Wing Check - Dec 10, 2025",
    upcomingAppointentTime: "23:45 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Luna",
    breed: "Beagle",
    species: "Dog",
    parent: "Ananya Gupta",
    gender: "Female",
    age: "5 years",
    lastMedication: "Tick Preventive (Oct 2025)",
    vaccineDue: "DHPP (Jan 2026)",
    upcomingAppointent: "Skin Allergy Review - Nov 29, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Buddy",
    breed: "Golden Retriever",
    species: "Dog",
    parent: "Aarav Mehta",
    gender: "Male",
    age: "4 years",
    lastMedication: "Heartworm Preventive (Sep 2025)",
    vaccineDue: "Rabies (Dec 2025)",
    upcomingAppointent: "General Checkup - Nov 20, 2025",
    upcomingAppointentTime: "03:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Misty",
    breed: "Siamese",
    species: "Cat",
    parent: "Ishita Roy",
    gender: "Female",
    age: "2 years",
    lastMedication: "Flea Treatment (Oct 2025)",
    vaccineDue: "FVRCP (Nov 2025)",
    upcomingAppointent: "Dental Cleaning - Dec 3, 2025",
    upcomingAppointentTime: "09:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Rocky",
    breed: "German Shepherd",
    species: "Dog",
    parent: "Rohan Patel",
    gender: "Male",
    age: "6 years",
    lastMedication: "Arthritis Support (Aug 2025)",
    vaccineDue: "Bordetella (Jan 2026)",
    upcomingAppointent: "Vaccination - Nov 25, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Coco",
    breed: "Mini Lop",
    species: "Rabbit",
    parent: "Sneha Verma",
    gender: "Female",
    age: "1 year",
    lastMedication: "Deworming (Sep 2025)",
    vaccineDue: "Myxomatosis (Feb 2026)",
    upcomingAppointent: "Nail Trim - Nov 18, 2025",
    upcomingAppointentTime: "13:15 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Kiwi",
    breed: "Cockatiel",
    species: "Bird",
    parent: "Vikram Singh",
    gender: "Male",
    age: "3 years",
    lastMedication: "Parasite Control (Oct 2025)",
    vaccineDue: "Avian Influenza (Apr 2026)",
    upcomingAppointent: "Wing Check - Dec 10, 2025",
    upcomingAppointentTime: "23:45 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Luna",
    breed: "Beagle",
    species: "Dog",
    parent: "Ananya Gupta",
    gender: "Female",
    age: "5 years",
    lastMedication: "Tick Preventive (Oct 2025)",
    vaccineDue: "DHPP (Jan 2026)",
    upcomingAppointent: "Skin Allergy Review - Nov 29, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Buddy",
    breed: "Golden Retriever",
    species: "Dog",
    parent: "Aarav Mehta",
    gender: "Male",
    age: "4 years",
    lastMedication: "Heartworm Preventive (Sep 2025)",
    vaccineDue: "Rabies (Dec 2025)",
    upcomingAppointent: "General Checkup - Nov 20, 2025",
    upcomingAppointentTime: "03:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Misty",
    breed: "Siamese",
    species: "Cat",
    parent: "Ishita Roy",
    gender: "Female",
    age: "2 years",
    lastMedication: "Flea Treatment (Oct 2025)",
    vaccineDue: "FVRCP (Nov 2025)",
    upcomingAppointent: "Dental Cleaning - Dec 3, 2025",
    upcomingAppointentTime: "09:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Rocky",
    breed: "German Shepherd",
    species: "Dog",
    parent: "Rohan Patel",
    gender: "Male",
    age: "6 years",
    lastMedication: "Arthritis Support (Aug 2025)",
    vaccineDue: "Bordetella (Jan 2026)",
    upcomingAppointent: "Vaccination - Nov 25, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Coco",
    breed: "Mini Lop",
    species: "Rabbit",
    parent: "Sneha Verma",
    gender: "Female",
    age: "1 year",
    lastMedication: "Deworming (Sep 2025)",
    vaccineDue: "Myxomatosis (Feb 2026)",
    upcomingAppointent: "Nail Trim - Nov 18, 2025",
    upcomingAppointentTime: "13:15 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Kiwi",
    breed: "Cockatiel",
    species: "Bird",
    parent: "Vikram Singh",
    gender: "Male",
    age: "3 years",
    lastMedication: "Parasite Control (Oct 2025)",
    vaccineDue: "Avian Influenza (Apr 2026)",
    upcomingAppointent: "Wing Check - Dec 10, 2025",
    upcomingAppointentTime: "23:45 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Luna",
    breed: "Beagle",
    species: "Dog",
    parent: "Ananya Gupta",
    gender: "Female",
    age: "5 years",
    lastMedication: "Tick Preventive (Oct 2025)",
    vaccineDue: "DHPP (Jan 2026)",
    upcomingAppointent: "Skin Allergy Review - Nov 29, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Buddy",
    breed: "Golden Retriever",
    species: "Dog",
    parent: "Aarav Mehta",
    gender: "Male",
    age: "4 years",
    lastMedication: "Heartworm Preventive (Sep 2025)",
    vaccineDue: "Rabies (Dec 2025)",
    upcomingAppointent: "General Checkup - Nov 20, 2025",
    upcomingAppointentTime: "03:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Misty",
    breed: "Siamese",
    species: "Cat",
    parent: "Ishita Roy",
    gender: "Female",
    age: "2 years",
    lastMedication: "Flea Treatment (Oct 2025)",
    vaccineDue: "FVRCP (Nov 2025)",
    upcomingAppointent: "Dental Cleaning - Dec 3, 2025",
    upcomingAppointentTime: "09:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Rocky",
    breed: "German Shepherd",
    species: "Dog",
    parent: "Rohan Patel",
    gender: "Male",
    age: "6 years",
    lastMedication: "Arthritis Support (Aug 2025)",
    vaccineDue: "Bordetella (Jan 2026)",
    upcomingAppointent: "Vaccination - Nov 25, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Coco",
    breed: "Mini Lop",
    species: "Rabbit",
    parent: "Sneha Verma",
    gender: "Female",
    age: "1 year",
    lastMedication: "Deworming (Sep 2025)",
    vaccineDue: "Myxomatosis (Feb 2026)",
    upcomingAppointent: "Nail Trim - Nov 18, 2025",
    upcomingAppointentTime: "13:15 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Kiwi",
    breed: "Cockatiel",
    species: "Bird",
    parent: "Vikram Singh",
    gender: "Male",
    age: "3 years",
    lastMedication: "Parasite Control (Oct 2025)",
    vaccineDue: "Avian Influenza (Apr 2026)",
    upcomingAppointent: "Wing Check - Dec 10, 2025",
    upcomingAppointentTime: "23:45 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Luna",
    breed: "Beagle",
    species: "Dog",
    parent: "Ananya Gupta",
    gender: "Female",
    age: "5 years",
    lastMedication: "Tick Preventive (Oct 2025)",
    vaccineDue: "DHPP (Jan 2026)",
    upcomingAppointent: "Skin Allergy Review - Nov 29, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Buddy",
    breed: "Golden Retriever",
    species: "Dog",
    parent: "Aarav Mehta",
    gender: "Male",
    age: "4 years",
    lastMedication: "Heartworm Preventive (Sep 2025)",
    vaccineDue: "Rabies (Dec 2025)",
    upcomingAppointent: "General Checkup - Nov 20, 2025",
    upcomingAppointentTime: "03:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Misty",
    breed: "Siamese",
    species: "Cat",
    parent: "Ishita Roy",
    gender: "Female",
    age: "2 years",
    lastMedication: "Flea Treatment (Oct 2025)",
    vaccineDue: "FVRCP (Nov 2025)",
    upcomingAppointent: "Dental Cleaning - Dec 3, 2025",
    upcomingAppointentTime: "09:15 PM",
    status: "active",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Rocky",
    breed: "German Shepherd",
    species: "Dog",
    parent: "Rohan Patel",
    gender: "Male",
    age: "6 years",
    lastMedication: "Arthritis Support (Aug 2025)",
    vaccineDue: "Bordetella (Jan 2026)",
    upcomingAppointent: "Vaccination - Nov 25, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Coco",
    breed: "Mini Lop",
    species: "Rabbit",
    parent: "Sneha Verma",
    gender: "Female",
    age: "1 year",
    lastMedication: "Deworming (Sep 2025)",
    vaccineDue: "Myxomatosis (Feb 2026)",
    upcomingAppointent: "Nail Trim - Nov 18, 2025",
    upcomingAppointentTime: "13:15 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Kiwi",
    breed: "Cockatiel",
    species: "Bird",
    parent: "Vikram Singh",
    gender: "Male",
    age: "3 years",
    lastMedication: "Parasite Control (Oct 2025)",
    vaccineDue: "Avian Influenza (Apr 2026)",
    upcomingAppointent: "Wing Check - Dec 10, 2025",
    upcomingAppointentTime: "23:45 PM",
    status: "inactive",
  },
  {
    image: "https://d2il6osz49gpup.cloudfront.net/Images/ftafter.png",
    name: "Luna",
    breed: "Beagle",
    species: "Dog",
    parent: "Ananya Gupta",
    gender: "Female",
    age: "5 years",
    lastMedication: "Tick Preventive (Oct 2025)",
    vaccineDue: "DHPP (Jan 2026)",
    upcomingAppointent: "Skin Allergy Review - Nov 29, 2025",
    upcomingAppointentTime: "03:15 AM",
    status: "archived",
  },
];
