export const fonts = {
  CLASH_DISPLAY_BOLD: 'ClashDisplay-Bold',
  CLASH_DISPLAY_EXTRA_LIGHT: 'ClashDisplay-Extralight',
  CLASH_DISPLAY_LIGHT: 'ClashDisplay-Light',
  CLASH_DISPLAY_MEDIUM: 'ClashDisplay-Medium',
  CLASH_DISPLAY_REGULAR: 'ClashDisplay-Regular',
  CLASH_DISPLAY_SEMIBOLD: 'ClashDisplay-Semibold',
  CLASH_DISPLAY_VARIABLE: 'ClashDisplay-Variable',
  CLASH_GRO_MEDIUM: 'ClashGrotesk-Medium',
  SATOSHI_BLACK: 'Satoshi-Black',
  SATOSHI_BOLD: 'Satoshi-Bold',
  SATOSHI_LIGHT: 'Satoshi-Light',
  SATOSHI_MEDIUM: 'Satoshi-Medium',
  SATOSHI_REGULAR: 'Satoshi-Regular',
  SF_PRO_TEXT_SEMIBOLD: 'SFProText-semibold',
  SF_PRO_TEXT_REGULAR: 'SFProText-regular',
} as const;

export const fontSizes = {
  xxs: 10,
  xs: 12,
  '13': 13,
  sm: 14,
  '15': 15,
  base: 16,
  lg: 18,
  '19': 19,
  xl: 20,
  '23': 23,
  '2xl': 24,
  '26': 26,
  '3xl': 30,
  '4xl': 36,
  '5xl': 48,
  '6xl': 60,
} as const;

export const fontWeights = {
  light: '300' as const,
  normal: '400' as const,
  medium: '500' as const,
  semibold: '600' as const,
  bold: '700' as const,
  black: '900' as const,
} as const;

export const lineHeights = {
  none: 1,
  tight: 1.25,
  snug: 1.375,
  normal: 1.5,
  relaxed: 1.625,
  loose: 2,
} as const;

export const typography = {
  // Headings
  h1: {
    fontFamily: fonts.CLASH_DISPLAY_BOLD,
    fontSize: fontSizes['4xl'],
    lineHeight: fontSizes['4xl'] * lineHeights.tight,
    fontWeight: fontWeights.bold,
  },
  h2: {
    fontFamily: fonts.CLASH_DISPLAY_BOLD,
    fontSize: fontSizes['3xl'],
    lineHeight: fontSizes['3xl'] * lineHeights.tight,
    fontWeight: fontWeights.bold,
  },
  h3: {
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    fontSize: fontSizes['26'],
    lineHeight: fontSizes['26'] * 1.2,
    fontWeight: fontWeights.medium,
    letterSpacing: -0.26,
  },
  h4: {
    fontFamily: fonts.CLASH_DISPLAY_SEMIBOLD,
    fontSize: fontSizes.xl,
    lineHeight: fontSizes.xl * lineHeights.snug,
    fontWeight: fontWeights.semibold,
  },
  h5: {
    fontFamily: fonts.CLASH_DISPLAY_MEDIUM,
    fontSize: fontSizes.lg,
    lineHeight: fontSizes.lg * lineHeights.normal,
    fontWeight: fontWeights.medium,
  },
  h6: {
    fontFamily: fonts.CLASH_DISPLAY_MEDIUM,
    fontSize: fontSizes.base,
    lineHeight: fontSizes.base * lineHeights.normal,
    fontWeight: fontWeights.medium,
  },
  titleLarge: {
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    fontSize: fontSizes.xl,
    lineHeight: fontSizes.xl * 1.2,
    fontWeight: fontWeights.medium,
    letterSpacing: -0.2,
  },
  titleMedium: {
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    fontSize: fontSizes.lg,
    lineHeight: fontSizes.lg * 1.2,
    fontWeight: fontWeights.medium,
    letterSpacing: -0.18,
  },
  titleSmall: {
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    fontSize: fontSizes.base,
    lineHeight: fontSizes.base * 1.2,
    fontWeight: fontWeights.medium,
    letterSpacing: -0.16,
  },
  paragraph: {
    fontFamily: fonts.SATOSHI_REGULAR,
    fontSize: fontSizes.base,
    lineHeight: fontSizes.base * 1.2,
    fontWeight: fontWeights.normal,
    letterSpacing: -0.32,
  },
  paragraphBold: {
    fontFamily: fonts.SATOSHI_BOLD,
    fontSize: fontSizes.base,
    lineHeight: fontSizes.base * 1.2,
    fontWeight: fontWeights.bold,
    letterSpacing: -0.32,
  },
  cta: {
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    fontSize: fontSizes.lg,
    lineHeight: fontSizes.lg,
    fontWeight: fontWeights.medium,
    letterSpacing: -0.18,
  },

  // Body text
  bodyLarge: {
    fontFamily: fonts.SATOSHI_REGULAR,
    fontSize: fontSizes.lg,
    lineHeight: fontSizes.lg * lineHeights.relaxed,
    fontWeight: fontWeights.normal,
  },
  body: {
    fontFamily: fonts.SATOSHI_REGULAR,
    fontSize: fontSizes.base,
    lineHeight: fontSizes.base * lineHeights.normal,
    fontWeight: fontWeights.normal,
  },
  bodySmall: {
    fontFamily: fonts.SATOSHI_REGULAR,
    fontSize: fontSizes.sm,
    lineHeight: fontSizes.sm * lineHeights.normal,
    fontWeight: fontWeights.normal,
  },
  bodySmallTight: {
    fontFamily: fonts.SATOSHI_REGULAR,
    fontSize: fontSizes.sm,
    lineHeight: fontSizes.sm * 1.4,
    fontWeight: fontWeights.normal,
  },
  bodyExtraSmall: {
    fontFamily: fonts.SATOSHI_REGULAR,
    fontSize: fontSizes['13'],
    lineHeight: fontSizes.base,
    fontWeight: fontWeights.normal,
  },
  bodyMedium: {
    fontFamily: fonts.SATOSHI_MEDIUM,
    fontSize: fontSizes.base,
    lineHeight: fontSizes.base * 1.5,
    fontWeight: fontWeights.medium,
  },

  // Labels
  label: {
    fontFamily: fonts.SATOSHI_MEDIUM,
    fontSize: fontSizes.base,
    lineHeight: fontSizes.base * lineHeights.normal,
    fontWeight: fontWeights.medium,
  },
  labelSmall: {
    fontFamily: fonts.SATOSHI_MEDIUM,
    fontSize: fontSizes.sm,
    lineHeight: fontSizes.sm * lineHeights.normal,
    fontWeight: fontWeights.medium,
  },
  labelSmallBold: {
    fontFamily: fonts.SATOSHI_BOLD,
    fontSize: fontSizes.sm,
    lineHeight: fontSizes.sm * lineHeights.normal,
    fontWeight: fontWeights.bold,
  },
  labelXs: {
    fontFamily: fonts.SATOSHI_MEDIUM,
    fontSize: fontSizes.xs,
    lineHeight: fontSizes.xs * lineHeights.normal,
    fontWeight: fontWeights.medium,
  },
  labelXxsBold: {
    fontFamily: fonts.SATOSHI_BOLD,
    fontSize: fontSizes.xs,
    lineHeight: fontSizes.xs * 1.2,
    fontWeight: fontWeights.bold,
    letterSpacing: 0,
  },

  // Captions
  caption: {
    fontFamily: fonts.SF_PRO_TEXT_REGULAR,
    fontSize: fontSizes.xs,
    lineHeight: fontSizes.xs * lineHeights.normal,
    fontWeight: fontWeights.normal,
  },
  captionBold: {
    fontFamily: fonts.SF_PRO_TEXT_SEMIBOLD,
    fontSize: fontSizes.xs,
    lineHeight: fontSizes.xs * lineHeights.normal,
    fontWeight: fontWeights.semibold,
  },

  // Buttons
  button: {
    fontFamily: fonts.SATOSHI_MEDIUM,
    fontSize: fontSizes.base,
    lineHeight: fontSizes.base * lineHeights.tight,
    fontWeight: fontWeights.medium,
  },
  buttonSmall: {
    fontFamily: fonts.SATOSHI_MEDIUM,
    fontSize: fontSizes.sm,
    lineHeight: fontSizes.sm * lineHeights.none,
    fontWeight: fontWeights.medium,
  },
  screenTitle: {
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    fontSize: fontSizes.base,
    lineHeight: fontSizes.base * 1.2,
    fontWeight: fontWeights.medium,
    letterSpacing: -0.16,
  },
  inputLabel: {
    fontFamily: fonts.SATOSHI_BOLD,
    fontSize: fontSizes.sm,
    lineHeight: fontSizes.base,
    fontWeight: fontWeights.bold,
    letterSpacing: -0.42,
  },
  input: {
    fontFamily: fonts.SATOSHI_REGULAR,
    fontSize: fontSizes.base,
    lineHeight: fontSizes.base * 1.2,
    fontWeight: fontWeights.normal,
    letterSpacing: -0.32,
  },
  inputFilled: {
    fontFamily: fonts.SATOSHI_MEDIUM,
    fontSize: fontSizes.base,
    lineHeight: fontSizes.base,
    fontWeight: fontWeights.medium,
    letterSpacing: -0.48,
  },
  inputError: {
    fontFamily: fonts.SATOSHI_BOLD,
    fontSize: fontSizes.sm,
    lineHeight: fontSizes.base,
    fontWeight: fontWeights.bold,
    letterSpacing: -0.42,
  },
  tabLabelFocused: {
    fontFamily: fonts.SATOSHI_BLACK,
    fontSize: fontSizes.xs,
    lineHeight: fontSizes.xs * 1.2,
    fontWeight: fontWeights.black,
  },
  tabLabel: {
    fontFamily: fonts.SATOSHI_MEDIUM,
    fontSize: fontSizes.xs,
    lineHeight: fontSizes.xs * 1.2,
    fontWeight: fontWeights.medium,
  },
  h4Alt: {
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    fontSize: fontSizes['23'],
    lineHeight: fontSizes['23'] * 1.2,
    fontWeight: fontWeights.medium,
    letterSpacing: -0.23,
  },
  paragraph18Bold: {
    fontFamily: fonts.SATOSHI_BOLD,
    fontSize: fontSizes.lg,
    lineHeight: fontSizes.lg * 1.2,
    fontWeight: fontWeights.bold,
    letterSpacing: -0.36,
  },
  subtitleBold14: {
    fontFamily: fonts.SATOSHI_BOLD,
    opacity: 0.6,
    fontSize: fontSizes.sm,
    lineHeight: fontSizes.sm * 1.2,
    fontWeight: fontWeights.bold,
  },
  clashBody13: {
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    fontSize: fontSizes['13'],
    lineHeight: fontSizes['13'] * 1.2,
    fontWeight: fontWeights.medium,
    letterSpacing: -0.13,
  },
  buttonLarge: {
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    fontSize: fontSizes['19'],
    lineHeight: fontSizes['19'] * 1.2,
    fontWeight: fontWeights.medium,
    letterSpacing: -0.38,
  },
  h6Clash: {
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    fontSize: fontSizes.lg,
    lineHeight: fontSizes.lg * 1.2,
    fontWeight: fontWeights.medium,
    letterSpacing: -0.18,
  },
  captionBoldSatoshi: {
    fontFamily: fonts.SATOSHI_BOLD,
    fontSize: fontSizes['13'],
    lineHeight: fontSizes['13'] * 1.2,
    fontWeight: fontWeights.bold,
    letterSpacing: 0,
  },

  // Appointments/Browse: additional tokens for card/pills parity
  subtitleBold12: {
    fontFamily: fonts.SATOSHI_BOLD,
    fontSize: fontSizes.xs,
    lineHeight: fontSizes.xs * 1.2,
    fontWeight: fontWeights.bold,
  },
  body12: {
    fontFamily: fonts.SATOSHI_REGULAR,
    fontSize: fontSizes.xs,
    lineHeight: fontSizes.xs * 1.3,
    fontWeight: fontWeights.normal,
  },
  pillSubtitleBold15: {
    fontFamily: fonts.SATOSHI_BOLD,
    fontSize: fontSizes['15'],
    lineHeight: fontSizes['2xl'],
    fontWeight: fontWeights.bold,
    letterSpacing: -0.3,
  },
  businessSectionTitle20: {
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    fontSize: fontSizes.xl,
    lineHeight: fontSizes['2xl'],
    fontWeight: fontWeights.medium,
    letterSpacing: -0.2,
  },
  subtitleRegular14: {
    fontFamily: fonts.SATOSHI_REGULAR,
    fontSize: fontSizes.sm,
    lineHeight: fontSizes.sm * 1.2,
    fontWeight: fontWeights.normal,
  },
} as const;
