ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'PARENT';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'COMPANION';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PARENT_ALERT_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PARENT_ALERT_UPDATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PARENT_ALERT_DELETED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'COMPANION_ALERT_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'COMPANION_ALERT_UPDATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'COMPANION_ALERT_DELETED';
