import {StyleSheet} from 'react-native';

export const createAttachmentStyles = (theme: any) =>
  StyleSheet.create({
    emptyStateContainer: {
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      borderRadius: theme.borderRadius.lg,
      paddingVertical: theme.spacing[8],
      paddingHorizontal: theme.spacing[4],
      alignItems: 'center',
      gap: theme.spacing[2],
      backgroundColor: theme.colors.surface,
    },
    emptyStateIcon: {
      width: 64,
      height: 64,
      resizeMode: 'contain',
    },
    emptyStateTitle: {
      ...theme.typography.titleMedium,
      color: theme.colors.secondary,
    },
    emptyStateSubtitle: {
      ...theme.typography.bodySmall,
      color: theme.colors.textSecondary,
      textAlign: 'center',
    },
    container: {gap: theme.spacing[4]},
    previewCard: {
      backgroundColor: theme.colors.cardBackground,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing[4],
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      alignItems: 'center',
      width: '100%',
      gap: theme.spacing[3],
    },
    previewCardHeader: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    previewImage: {
      width: '100%',
      height: 400,
      borderRadius: theme.borderRadius.base,
      marginBottom: theme.spacing[2],
    },
    pdfPlaceholder: {
      width: '100%',
      height: 300,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.base,
      marginBottom: theme.spacing[2],
    },
    pdfIcon: {
      width: 64,
      height: 64,
      resizeMode: 'contain',
      marginBottom: theme.spacing[3],
    },
    pdfLabel: {
      ...theme.typography.bodySmall,
      color: theme.colors.textSecondary,
    },
    pageIndicator: {
      ...theme.typography.labelSmall,
      color: theme.colors.textSecondary,
    },
    actionRow: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: theme.spacing[4],
      marginTop: theme.spacing[2],
    },
    shareButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.colors.primary,
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: theme.spacing[4],
      marginBottom: theme.spacing[2],
      ...theme.shadows.md,
    },
    downloadButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.colors.secondary,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: theme.spacing[4],
      marginBottom: theme.spacing[2],
      ...theme.shadows.md,
    },
    shareIcon: {
      width: 28,
      height: 28,
      resizeMode: 'contain',
      tintColor: theme.colors.white,
    },
    downloadIcon: {
      width: 28,
      height: 28,
      resizeMode: 'contain',
      tintColor: theme.colors.white,
    },
  });

export default createAttachmentStyles;
