name: CI Website

on:
    pull_request:

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Add Jobs for Linting & Testing
jobs:
    changed-files-check:
      uses: ./.github/workflows/changed-files.yaml
      with:
        files: |
          package.json
          apps/frontend/**
    build:
        needs: changed-files-check
        if: needs.changed-files-check.outputs.any_changed == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with: 
                fetch-depth: 0
            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                run_install: false
            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'pnpm'
            # - name: Install pnpm
            #   run: npm install -g pnpm
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            # - name: Linting
            #   run: pnpm run lint --filter frontend
            - name: Build Website
              run: pnpm run build --filter frontend
    ci-website-status-check:
        if: always() && !cancelled()
        timeout-minutes: 1
        runs-on: ubuntu-latest
        needs: [changed-files-check, build]
        steps:
        - name: Fail job if any needs failed
          if: contains(needs.*.result, 'failure')
          run: exit 1